# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_osgDB', [dirname(__file__)])
        except ImportError:
            import _osgDB
            return _osgDB
        if fp is not None:
            try:
                _mod = imp.load_module('_osgDB', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _osgDB = swig_import_helper()
    del swig_import_helper
else:
    import _osgDB
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    """Proxy of C++ swig::SwigPyIterator class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _osgDB.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self):
        """value(self) -> PyObject"""
        return _osgDB.SwigPyIterator_value(self)

    def incr(self, n = 1):
        """
        incr(self, size_t n = 1) -> SwigPyIterator
        incr(self) -> SwigPyIterator
        """
        return _osgDB.SwigPyIterator_incr(self, n)

    def decr(self, n = 1):
        """
        decr(self, size_t n = 1) -> SwigPyIterator
        decr(self) -> SwigPyIterator
        """
        return _osgDB.SwigPyIterator_decr(self, n)

    def distance(self, *args):
        """distance(self, SwigPyIterator x) -> ptrdiff_t"""
        return _osgDB.SwigPyIterator_distance(self, *args)

    def equal(self, *args):
        """equal(self, SwigPyIterator x) -> bool"""
        return _osgDB.SwigPyIterator_equal(self, *args)

    def copy(self):
        """copy(self) -> SwigPyIterator"""
        return _osgDB.SwigPyIterator_copy(self)

    def next(self):
        """next(self) -> PyObject"""
        return _osgDB.SwigPyIterator_next(self)

    def __next__(self):
        """__next__(self) -> PyObject"""
        return _osgDB.SwigPyIterator___next__(self)

    def previous(self):
        """previous(self) -> PyObject"""
        return _osgDB.SwigPyIterator_previous(self)

    def advance(self, *args):
        """advance(self, ptrdiff_t n) -> SwigPyIterator"""
        return _osgDB.SwigPyIterator_advance(self, *args)

    def __eq__(self, *args):
        """__eq__(self, SwigPyIterator x) -> bool"""
        return _osgDB.SwigPyIterator___eq__(self, *args)

    def __ne__(self, *args):
        """__ne__(self, SwigPyIterator x) -> bool"""
        return _osgDB.SwigPyIterator___ne__(self, *args)

    def __iadd__(self, *args):
        """__iadd__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _osgDB.SwigPyIterator___iadd__(self, *args)

    def __isub__(self, *args):
        """__isub__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _osgDB.SwigPyIterator___isub__(self, *args)

    def __add__(self, *args):
        """__add__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _osgDB.SwigPyIterator___add__(self, *args)

    def __sub__(self, *args):
        """
        __sub__(self, ptrdiff_t n) -> SwigPyIterator
        __sub__(self, SwigPyIterator x) -> ptrdiff_t
        """
        return _osgDB.SwigPyIterator___sub__(self, *args)

    def __iter__(self): return self
SwigPyIterator_swigregister = _osgDB.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import osg
class stdFilePathList(_object):
    """Proxy of C++ std::deque<(std::string)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, stdFilePathList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, stdFilePathList, name)
    __repr__ = _swig_repr
    def iterator(self):
        """iterator(self) -> SwigPyIterator"""
        return _osgDB.stdFilePathList_iterator(self)

    def __iter__(self): return self.iterator()
    def __nonzero__(self):
        """__nonzero__(self) -> bool"""
        return _osgDB.stdFilePathList___nonzero__(self)

    def __bool__(self):
        """__bool__(self) -> bool"""
        return _osgDB.stdFilePathList___bool__(self)

    def __len__(self):
        """__len__(self) -> size_type"""
        return _osgDB.stdFilePathList___len__(self)

    def pop(self):
        """pop(self) -> value_type"""
        return _osgDB.stdFilePathList_pop(self)

    def __getslice__(self, *args):
        """__getslice__(self, difference_type i, difference_type j) -> stdFilePathList"""
        return _osgDB.stdFilePathList___getslice__(self, *args)

    def __setslice__(self, *args):
        """__setslice__(self, difference_type i, difference_type j, stdFilePathList v)"""
        return _osgDB.stdFilePathList___setslice__(self, *args)

    def __delslice__(self, *args):
        """__delslice__(self, difference_type i, difference_type j)"""
        return _osgDB.stdFilePathList___delslice__(self, *args)

    def __delitem__(self, *args):
        """
        __delitem__(self, difference_type i)
        __delitem__(self, PySliceObject slice)
        """
        return _osgDB.stdFilePathList___delitem__(self, *args)

    def __getitem__(self, *args):
        """
        __getitem__(self, PySliceObject slice) -> stdFilePathList
        __getitem__(self, difference_type i) -> value_type
        """
        return _osgDB.stdFilePathList___getitem__(self, *args)

    def __setitem__(self, *args):
        """
        __setitem__(self, PySliceObject slice, stdFilePathList v)
        __setitem__(self, difference_type i, value_type x)
        """
        return _osgDB.stdFilePathList___setitem__(self, *args)

    def append(self, *args):
        """append(self, value_type x)"""
        return _osgDB.stdFilePathList_append(self, *args)

    def empty(self):
        """empty(self) -> bool"""
        return _osgDB.stdFilePathList_empty(self)

    def size(self):
        """size(self) -> size_type"""
        return _osgDB.stdFilePathList_size(self)

    def clear(self):
        """clear(self)"""
        return _osgDB.stdFilePathList_clear(self)

    def swap(self, *args):
        """swap(self, stdFilePathList v)"""
        return _osgDB.stdFilePathList_swap(self, *args)

    def get_allocator(self):
        """get_allocator(self) -> allocator_type"""
        return _osgDB.stdFilePathList_get_allocator(self)

    def begin(self):
        """begin(self) -> const_iterator"""
        return _osgDB.stdFilePathList_begin(self)

    def end(self):
        """end(self) -> const_iterator"""
        return _osgDB.stdFilePathList_end(self)

    def rbegin(self):
        """rbegin(self) -> const_reverse_iterator"""
        return _osgDB.stdFilePathList_rbegin(self)

    def rend(self):
        """rend(self) -> const_reverse_iterator"""
        return _osgDB.stdFilePathList_rend(self)

    def pop_back(self):
        """pop_back(self)"""
        return _osgDB.stdFilePathList_pop_back(self)

    def erase(self, *args):
        """
        erase(self, iterator pos) -> iterator
        erase(self, iterator first, iterator last) -> iterator
        """
        return _osgDB.stdFilePathList_erase(self, *args)

    def __init__(self, *args): 
        """
        __init__(self) -> stdFilePathList
        __init__(self, stdFilePathList arg0) -> stdFilePathList
        __init__(self, size_type size) -> stdFilePathList
        __init__(self, size_type size, value_type value) -> stdFilePathList
        """
        this = _osgDB.new_stdFilePathList(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args):
        """push_back(self, value_type x)"""
        return _osgDB.stdFilePathList_push_back(self, *args)

    def front(self):
        """front(self) -> value_type"""
        return _osgDB.stdFilePathList_front(self)

    def back(self):
        """back(self) -> value_type"""
        return _osgDB.stdFilePathList_back(self)

    def assign(self, *args):
        """assign(self, size_type n, value_type x)"""
        return _osgDB.stdFilePathList_assign(self, *args)

    def resize(self, *args):
        """
        resize(self, size_type new_size)
        resize(self, size_type new_size, value_type x)
        """
        return _osgDB.stdFilePathList_resize(self, *args)

    def insert(self, *args):
        """
        insert(self, iterator pos, value_type x) -> iterator
        insert(self, iterator pos, size_type n, value_type x)
        """
        return _osgDB.stdFilePathList_insert(self, *args)

    def pop_front(self):
        """pop_front(self)"""
        return _osgDB.stdFilePathList_pop_front(self)

    def push_front(self, *args):
        """push_front(self, value_type x)"""
        return _osgDB.stdFilePathList_push_front(self, *args)

    __swig_destroy__ = _osgDB.delete_stdFilePathList
    __del__ = lambda self : None;
stdFilePathList_swigregister = _osgDB.stdFilePathList_swigregister
stdFilePathList_swigregister(stdFilePathList)

OSGDB_VERSION = _osgDB.OSGDB_VERSION

def osgDBGetVersion():
  """osgDBGetVersion() -> char"""
  return _osgDB.osgDBGetVersion()

def osgDBGetLibraryName():
  """osgDBGetLibraryName() -> char"""
  return _osgDB.osgDBGetLibraryName()
OSGDB_EXPORT_ = _osgDB.OSGDB_EXPORT_
OSGDB_AUTHENTICATIONMAP = _osgDB.OSGDB_AUTHENTICATIONMAP
class AuthenticationDetails(osg.Referenced):
    """Proxy of C++ osgDB::AuthenticationDetails class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AuthenticationDetails, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AuthenticationDetails, name)
    __repr__ = _swig_repr
    BASIC = _osgDB.AuthenticationDetails_BASIC
    DIGEST = _osgDB.AuthenticationDetails_DIGEST
    NTLM = _osgDB.AuthenticationDetails_NTLM
    GSSNegotiate = _osgDB.AuthenticationDetails_GSSNegotiate
    ANY = _osgDB.AuthenticationDetails_ANY
    ANYSAFE = _osgDB.AuthenticationDetails_ANYSAFE
    def __init__(self, *args): 
        """
        __init__(self, string u, string p, HttpAuthentication auth = BASIC) -> AuthenticationDetails
        __init__(self, string u, string p) -> AuthenticationDetails
        """
        this = _osgDB.new_AuthenticationDetails(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["username"] = _osgDB.AuthenticationDetails_username_set
    __swig_getmethods__["username"] = _osgDB.AuthenticationDetails_username_get
    if _newclass:username = _swig_property(_osgDB.AuthenticationDetails_username_get, _osgDB.AuthenticationDetails_username_set)
    __swig_setmethods__["password"] = _osgDB.AuthenticationDetails_password_set
    __swig_getmethods__["password"] = _osgDB.AuthenticationDetails_password_get
    if _newclass:password = _swig_property(_osgDB.AuthenticationDetails_password_get, _osgDB.AuthenticationDetails_password_set)
    __swig_setmethods__["httpAuthentication"] = _osgDB.AuthenticationDetails_httpAuthentication_set
    __swig_getmethods__["httpAuthentication"] = _osgDB.AuthenticationDetails_httpAuthentication_get
    if _newclass:httpAuthentication = _swig_property(_osgDB.AuthenticationDetails_httpAuthentication_get, _osgDB.AuthenticationDetails_httpAuthentication_set)
AuthenticationDetails_swigregister = _osgDB.AuthenticationDetails_swigregister
AuthenticationDetails_swigregister(AuthenticationDetails)

class AuthenticationMap(osg.Referenced):
    """Proxy of C++ osgDB::AuthenticationMap class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AuthenticationMap, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AuthenticationMap, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> AuthenticationMap"""
        this = _osgDB.new_AuthenticationMap()
        try: self.this.append(this)
        except: self.this = this
    def addAuthenticationDetails(self, *args):
        """addAuthenticationDetails(self, string path, AuthenticationDetails details)"""
        return _osgDB.AuthenticationMap_addAuthenticationDetails(self, *args)

    def getAuthenticationDetails(self, *args):
        """getAuthenticationDetails(self, string path) -> AuthenticationDetails"""
        return _osgDB.AuthenticationMap_getAuthenticationDetails(self, *args)

AuthenticationMap_swigregister = _osgDB.AuthenticationMap_swigregister
AuthenticationMap_swigregister(AuthenticationMap)

OSGDB_FILECACHE = _osgDB.OSGDB_FILECACHE
class FileCache(osg.Referenced):
    """Proxy of C++ osgDB::FileCache class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FileCache, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, FileCache, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, string path) -> FileCache"""
        this = _osgDB.new_FileCache(*args)
        try: self.this.append(this)
        except: self.this = this
    def getFileCachePath(self):
        """getFileCachePath(self) -> string"""
        return _osgDB.FileCache_getFileCachePath(self)

    def isFileAppropriateForFileCache(self, *args):
        """isFileAppropriateForFileCache(self, string originalFileName) -> bool"""
        return _osgDB.FileCache_isFileAppropriateForFileCache(self, *args)

    def createCacheFileName(self, *args):
        """createCacheFileName(self, string originalFileName) -> string"""
        return _osgDB.FileCache_createCacheFileName(self, *args)

    def existsInCache(self, *args):
        """existsInCache(self, string originalFileName) -> bool"""
        return _osgDB.FileCache_existsInCache(self, *args)

    def readImage(self, *args):
        """readImage(self, string originalFileName, Options options) -> ReaderWriter::ReadResult"""
        return _osgDB.FileCache_readImage(self, *args)

    def writeImage(self, *args):
        """writeImage(self, Image image, string originalFileName, Options options) -> ReaderWriter::WriteResult"""
        return _osgDB.FileCache_writeImage(self, *args)

    def readObject(self, *args):
        """readObject(self, string originalFileName, Options options) -> ReaderWriter::ReadResult"""
        return _osgDB.FileCache_readObject(self, *args)

    def writeObject(self, *args):
        """writeObject(self, Object object, string originalFileName, Options options) -> ReaderWriter::WriteResult"""
        return _osgDB.FileCache_writeObject(self, *args)

    def readHeightField(self, *args):
        """readHeightField(self, string originalFileName, Options options) -> ReaderWriter::ReadResult"""
        return _osgDB.FileCache_readHeightField(self, *args)

    def writeHeightField(self, *args):
        """writeHeightField(self, HeightField hf, string originalFileName, Options options) -> ReaderWriter::WriteResult"""
        return _osgDB.FileCache_writeHeightField(self, *args)

    def readNode(self, *args):
        """
        readNode(self, string originalFileName, Options options, bool buildKdTreeIfRequired = True) -> ReaderWriter::ReadResult
        readNode(self, string originalFileName, Options options) -> ReaderWriter::ReadResult
        """
        return _osgDB.FileCache_readNode(self, *args)

    def writeNode(self, *args):
        """writeNode(self, Node node, string originalFileName, Options options) -> ReaderWriter::WriteResult"""
        return _osgDB.FileCache_writeNode(self, *args)

    def readShader(self, *args):
        """readShader(self, string originalFileName, Options options) -> ReaderWriter::ReadResult"""
        return _osgDB.FileCache_readShader(self, *args)

    def writeShader(self, *args):
        """writeShader(self, Shader shader, string originalFileName, Options options) -> ReaderWriter::WriteResult"""
        return _osgDB.FileCache_writeShader(self, *args)

    def loadDatabaseRevisionsForFile(self, *args):
        """loadDatabaseRevisionsForFile(self, string originanlFileName) -> bool"""
        return _osgDB.FileCache_loadDatabaseRevisionsForFile(self, *args)

    def getDatabaseRevisionsList(self):
        """getDatabaseRevisionsList(self) -> DatabaseRevisionsList"""
        return _osgDB.FileCache_getDatabaseRevisionsList(self)

    def isCachedFileBlackListed(self, *args):
        """isCachedFileBlackListed(self, string originalFileName) -> bool"""
        return _osgDB.FileCache_isCachedFileBlackListed(self, *args)

FileCache_swigregister = _osgDB.FileCache_swigregister
FileCache_swigregister(FileCache)

OSGDB_READERWRITER = _osgDB.OSGDB_READERWRITER
OSGDB_WRITEFILE = _osgDB.OSGDB_WRITEFILE
OSGDB_SHAREDSTATEMANAGER = _osgDB.OSGDB_SHAREDSTATEMANAGER
class SharedStateManager(osg.NodeVisitor):
    """Proxy of C++ osgDB::SharedStateManager class"""
    __swig_setmethods__ = {}
    for _s in [osg.NodeVisitor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SharedStateManager, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.NodeVisitor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SharedStateManager, name)
    __repr__ = _swig_repr
    SHARE_NONE = _osgDB.SharedStateManager_SHARE_NONE
    SHARE_STATIC_TEXTURES = _osgDB.SharedStateManager_SHARE_STATIC_TEXTURES
    SHARE_UNSPECIFIED_TEXTURES = _osgDB.SharedStateManager_SHARE_UNSPECIFIED_TEXTURES
    SHARE_DYNAMIC_TEXTURES = _osgDB.SharedStateManager_SHARE_DYNAMIC_TEXTURES
    SHARE_STATIC_STATESETS = _osgDB.SharedStateManager_SHARE_STATIC_STATESETS
    SHARE_UNSPECIFIED_STATESETS = _osgDB.SharedStateManager_SHARE_UNSPECIFIED_STATESETS
    SHARE_DYNAMIC_STATESETS = _osgDB.SharedStateManager_SHARE_DYNAMIC_STATESETS
    SHARE_TEXTURES = _osgDB.SharedStateManager_SHARE_TEXTURES
    SHARE_STATESETS = _osgDB.SharedStateManager_SHARE_STATESETS
    SHARE_ALL = _osgDB.SharedStateManager_SHARE_ALL
    def __init__(self, *args): 
        """
        __init__(self, unsigned int mode = SHARE_ALL) -> SharedStateManager
        __init__(self) -> SharedStateManager
        """
        this = _osgDB.new_SharedStateManager(*args)
        try: self.this.append(this)
        except: self.this = this
    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgDB.SharedStateManager_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgDB.SharedStateManager_className(self)

    def setShareMode(self, *args):
        """setShareMode(self, unsigned int mode)"""
        return _osgDB.SharedStateManager_setShareMode(self, *args)

    def getShareMode(self):
        """getShareMode(self) -> unsigned int"""
        return _osgDB.SharedStateManager_getShareMode(self)

    def prune(self):
        """prune(self)"""
        return _osgDB.SharedStateManager_prune(self)

    def share(self, *args):
        """
        share(self, Node node, OpenThreads::Mutex mt = None)
        share(self, Node node)
        """
        return _osgDB.SharedStateManager_share(self, *args)

    def apply(self, *args):
        """
        apply(self, Node node)
        apply(self, Geode geode)
        """
        return _osgDB.SharedStateManager_apply(self, *args)

    def isShared(self, *args):
        """
        isShared(self, StateSet stateSet) -> bool
        isShared(self, Texture texture) -> bool
        """
        return _osgDB.SharedStateManager_isShared(self, *args)

    def releaseGLObjects(self, *args):
        """releaseGLObjects(self, State state)"""
        return _osgDB.SharedStateManager_releaseGLObjects(self, *args)

    __swig_destroy__ = _osgDB.delete_SharedStateManager
    __del__ = lambda self : None;
SharedStateManager_swigregister = _osgDB.SharedStateManager_swigregister
SharedStateManager_swigregister(SharedStateManager)

def writeObjectFile(*args):
  """
    writeObjectFile(Object object, string filename, Options options) -> bool
    writeObjectFile(Object object, string filename) -> bool
    """
  return _osgDB.writeObjectFile(*args)

def writeImageFile(*args):
  """
    writeImageFile(Image image, string filename, Options options) -> bool
    writeImageFile(Image image, string filename) -> bool
    """
  return _osgDB.writeImageFile(*args)

def writeHeightFieldFile(*args):
  """
    writeHeightFieldFile(HeightField hf, string filename, Options options) -> bool
    writeHeightFieldFile(HeightField hf, string filename) -> bool
    """
  return _osgDB.writeHeightFieldFile(*args)

def writeNodeFile(*args):
  """
    writeNodeFile(Node node, string filename, Options options) -> bool
    writeNodeFile(Node node, string filename) -> bool
    """
  return _osgDB.writeNodeFile(*args)

def writeShaderFile(*args):
  """
    writeShaderFile(Shader shader, string filename, Options options) -> bool
    writeShaderFile(Shader shader, string filename) -> bool
    """
  return _osgDB.writeShaderFile(*args)

OSGDB_READFILE = _osgDB.OSGDB_READFILE
OSGDB_INPUT = _osgDB.OSGDB_INPUT
class Field(_object):
    """Proxy of C++ osgDB::Field class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Field, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Field, name)
    __repr__ = _swig_repr
    MIN_CACHE_SIZE = _osgDB.Field_MIN_CACHE_SIZE
    def __init__(self, *args): 
        """
        __init__(self) -> Field
        __init__(self, Field field) -> Field
        """
        this = _osgDB.new_Field(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _osgDB.delete_Field
    __del__ = lambda self : None;
    def reset(self):
        """reset(self)"""
        return _osgDB.Field_reset(self)

    def addChar(self, *args):
        """addChar(self, char c)"""
        return _osgDB.Field_addChar(self, *args)

    def getNoCharacters(self):
        """getNoCharacters(self) -> int"""
        return _osgDB.Field_getNoCharacters(self)

    def setWithinQuotes(self, withinQuotes = True):
        """
        setWithinQuotes(self, bool withinQuotes = True)
        setWithinQuotes(self)
        """
        return _osgDB.Field_setWithinQuotes(self, withinQuotes)

    def getWithinQuotes(self):
        """getWithinQuotes(self) -> bool"""
        return _osgDB.Field_getWithinQuotes(self)

    def setNoNestedBrackets(self, *args):
        """setNoNestedBrackets(self, int no)"""
        return _osgDB.Field_setNoNestedBrackets(self, *args)

    def getNoNestedBrackets(self):
        """getNoNestedBrackets(self) -> int"""
        return _osgDB.Field_getNoNestedBrackets(self)

    OPEN_BRACKET = _osgDB.Field_OPEN_BRACKET
    CLOSE_BRACKET = _osgDB.Field_CLOSE_BRACKET
    STRING = _osgDB.Field_STRING
    WORD = _osgDB.Field_WORD
    REAL = _osgDB.Field_REAL
    INTEGER = _osgDB.Field_INTEGER
    BLANK = _osgDB.Field_BLANK
    UNINITIALISED = _osgDB.Field_UNINITIALISED
    def getFieldType(self):
        """getFieldType(self) -> FieldType"""
        return _osgDB.Field_getFieldType(self)

    def isValid(self):
        """isValid(self) -> bool"""
        return _osgDB.Field_isValid(self)

    def isOpenBracket(self):
        """isOpenBracket(self) -> bool"""
        return _osgDB.Field_isOpenBracket(self)

    def isCloseBracket(self):
        """isCloseBracket(self) -> bool"""
        return _osgDB.Field_isCloseBracket(self)

    def isWord(self):
        """isWord(self) -> bool"""
        return _osgDB.Field_isWord(self)

    def matchWord(self, *args):
        """
        matchWord(self, char str) -> bool
        matchWord(self, char str, int noCharacters) -> bool
        """
        return _osgDB.Field_matchWord(self, *args)

    def isString(self):
        """isString(self) -> bool"""
        return _osgDB.Field_isString(self)

    def matchString(self, *args):
        """
        matchString(self, char str) -> bool
        matchString(self, char str, int noCharacters) -> bool
        """
        return _osgDB.Field_matchString(self, *args)

    def isQuotedString(self):
        """isQuotedString(self) -> bool"""
        return _osgDB.Field_isQuotedString(self)

    def getStr(self):
        """getStr(self) -> char"""
        return _osgDB.Field_getStr(self)

    def takeStr(self):
        """takeStr(self) -> char"""
        return _osgDB.Field_takeStr(self)

    def isInt(self):
        """isInt(self) -> bool"""
        return _osgDB.Field_isInt(self)

    def matchInt(self, *args):
        """matchInt(self, int i) -> bool"""
        return _osgDB.Field_matchInt(self, *args)

    def getInt(self):
        """getInt(self) -> bool"""
        return _osgDB.Field_getInt(self)

    def isUInt(self):
        """isUInt(self) -> bool"""
        return _osgDB.Field_isUInt(self)

    def matchUInt(self, *args):
        """matchUInt(self, unsigned int i) -> bool"""
        return _osgDB.Field_matchUInt(self, *args)

    def getUInt(self, *args):
        """getUInt(self, unsigned int i) -> bool"""
        return _osgDB.Field_getUInt(self, *args)

    def isFloat(self):
        """isFloat(self) -> bool"""
        return _osgDB.Field_isFloat(self)

    def matchFloat(self, *args):
        """matchFloat(self, float f) -> bool"""
        return _osgDB.Field_matchFloat(self, *args)

    def getFloat(self, *args):
        """
        getFloat(self) -> bool
        getFloat(self, double f) -> bool
        """
        return _osgDB.Field_getFloat(self, *args)

    def calculateFieldType(*args):
        """
        calculateFieldType(char str, bool withinQuotes = False) -> FieldType
        calculateFieldType(char str) -> FieldType
        """
        return _osgDB.Field_calculateFieldType(*args)

    if _newclass:calculateFieldType = staticmethod(calculateFieldType)
    __swig_getmethods__["calculateFieldType"] = lambda x: calculateFieldType
Field_swigregister = _osgDB.Field_swigregister
Field_swigregister(Field)

def readObjectFile(*args):
  """
    readObjectFile(string filename, Options options) -> Object
    readObjectFile(string filename) -> Object
    """
  return _osgDB.readObjectFile(*args)

def readImageFile(*args):
  """
    readImageFile(string filename, Options options) -> Image
    readImageFile(string filename) -> Image
    """
  return _osgDB.readImageFile(*args)

def readHeightFieldFile(*args):
  """
    readHeightFieldFile(string filename, Options options) -> HeightField
    readHeightFieldFile(string filename) -> HeightField
    """
  return _osgDB.readHeightFieldFile(*args)

def readNodeFile(*args):
  """
    readNodeFile(string filename, Options options) -> Node
    readNodeFile(string filename) -> Node
    """
  return _osgDB.readNodeFile(*args)

def readNodeFiles(*args):
  """
    readNodeFiles(__dummy_0__ fileList, Options options) -> Node
    readNodeFiles(__dummy_0__ fileList) -> Node
    readNodeFiles(ArgumentParser parser, Options options) -> Node
    readNodeFiles(ArgumentParser parser) -> Node
    """
  return _osgDB.readNodeFiles(*args)

def readShaderFile(*args):
  """
    readShaderFile(string filename, Options options) -> Shader
    readShaderFile(string filename) -> Shader
    readShaderFile(Type type, string filename, Options options) -> Shader
    readShaderFile(Type type, string filename) -> Shader
    """
  return _osgDB.readShaderFile(*args)

def readRefObjectFile(*args):
  """
    readRefObjectFile(string filename, Options options) -> osg::ref_ptr<(osg::Object)>
    readRefObjectFile(string filename) -> osg::ref_ptr<(osg::Object)>
    """
  return _osgDB.readRefObjectFile(*args)

def readRefImageFile(*args):
  """
    readRefImageFile(string filename, Options options) -> ImageRef
    readRefImageFile(string filename) -> ImageRef
    """
  return _osgDB.readRefImageFile(*args)

def readRefHeightFieldFile(*args):
  """
    readRefHeightFieldFile(string filename, Options options) -> osg::ref_ptr<(osg::HeightField)>
    readRefHeightFieldFile(string filename) -> osg::ref_ptr<(osg::HeightField)>
    """
  return _osgDB.readRefHeightFieldFile(*args)

def readRefNodeFile(*args):
  """
    readRefNodeFile(string filename, Options options) -> NodeRef
    readRefNodeFile(string filename) -> NodeRef
    """
  return _osgDB.readRefNodeFile(*args)

def readRefShaderFile(*args):
  """
    readRefShaderFile(string filename, Options options) -> osg::ref_ptr<(osg::Shader)>
    readRefShaderFile(string filename) -> osg::ref_ptr<(osg::Shader)>
    """
  return _osgDB.readRefShaderFile(*args)

def Field_calculateFieldType(*args):
  """
    calculateFieldType(char str, bool withinQuotes = False) -> FieldType
    Field_calculateFieldType(char str) -> FieldType
    """
  return _osgDB.Field_calculateFieldType(*args)

class FieldReader(_object):
    """Proxy of C++ osgDB::FieldReader class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FieldReader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FieldReader, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> FieldReader
        __init__(self, FieldReader ic) -> FieldReader
        """
        this = _osgDB.new_FieldReader(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _osgDB.delete_FieldReader
    __del__ = lambda self : None;
    def attach(self, *args):
        """attach(self, std::istream input)"""
        return _osgDB.FieldReader_attach(self, *args)

    def detach(self):
        """detach(self)"""
        return _osgDB.FieldReader_detach(self)

    def eof(self):
        """eof(self) -> bool"""
        return _osgDB.FieldReader_eof(self)

    def readField(self, *args):
        """readField(self, Field fieldPtr) -> bool"""
        return _osgDB.FieldReader_readField(self, *args)

    def ignoreField(self):
        """ignoreField(self)"""
        return _osgDB.FieldReader_ignoreField(self)

    def getNoNestedBrackets(self):
        """getNoNestedBrackets(self) -> int"""
        return _osgDB.FieldReader_getNoNestedBrackets(self)

FieldReader_swigregister = _osgDB.FieldReader_swigregister
FieldReader_swigregister(FieldReader)

class FieldReaderIterator(_object):
    """Proxy of C++ osgDB::FieldReaderIterator class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FieldReaderIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FieldReaderIterator, name)
    __repr__ = _swig_repr
    MINIMUM_FIELD_READER_QUEUE_SIZE = _osgDB.FieldReaderIterator_MINIMUM_FIELD_READER_QUEUE_SIZE
    def __init__(self, *args): 
        """
        __init__(self) -> FieldReaderIterator
        __init__(self, FieldReaderIterator ic) -> FieldReaderIterator
        """
        this = _osgDB.new_FieldReaderIterator(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _osgDB.delete_FieldReaderIterator
    __del__ = lambda self : None;
    def attach(self, *args):
        """attach(self, std::istream input)"""
        return _osgDB.FieldReaderIterator_attach(self, *args)

    def detach(self):
        """detach(self)"""
        return _osgDB.FieldReaderIterator_detach(self)

    def eof(self):
        """eof(self) -> bool"""
        return _osgDB.FieldReaderIterator_eof(self)

    def getFieldReader(self):
        """getFieldReader(self) -> FieldReader"""
        return _osgDB.FieldReaderIterator_getFieldReader(self)

    def insert(self, *args):
        """
        insert(self, int pos, Field field)
        insert(self, int pos, char str)
        """
        return _osgDB.FieldReaderIterator_insert(self, *args)

    def field(self, *args):
        """field(self, int pos) -> Field"""
        return _osgDB.FieldReaderIterator_field(self, *args)

    def __iadd__(self, *args):
        """__iadd__(self, int no) -> FieldReaderIterator"""
        return _osgDB.FieldReaderIterator___iadd__(self, *args)

    def advanceOverCurrentFieldOrBlock(self):
        """advanceOverCurrentFieldOrBlock(self)"""
        return _osgDB.FieldReaderIterator_advanceOverCurrentFieldOrBlock(self)

    def advanceToEndOfCurrentBlock(self):
        """advanceToEndOfCurrentBlock(self)"""
        return _osgDB.FieldReaderIterator_advanceToEndOfCurrentBlock(self)

    def advanceToEndOfBlock(self, *args):
        """advanceToEndOfBlock(self, int noNestBrackets)"""
        return _osgDB.FieldReaderIterator_advanceToEndOfBlock(self, *args)

    def matchSequence(self, *args):
        """matchSequence(self, char str) -> bool"""
        return _osgDB.FieldReaderIterator_matchSequence(self, *args)

    def readSequence(self, *args):
        """
        readSequence(self, char keyword, string value) -> bool
        readSequence(self, char keyword, unsigned int value) -> bool
        readSequence(self, char keyword, int value) -> bool
        readSequence(self, char keyword, float value) -> bool
        readSequence(self, char keyword, Vec2f value) -> bool
        readSequence(self, char keyword, Vec3f value) -> bool
        readSequence(self, char keyword, Vec4f value) -> bool
        readSequence(self, char keyword, Vec2d value) -> bool
        readSequence(self, char keyword, Vec3d value) -> bool
        readSequence(self, char keyword, Vec4d value) -> bool
        readSequence(self, string value) -> bool
        readSequence(self, unsigned int value) -> bool
        readSequence(self, int value) -> bool
        readSequence(self, float value) -> bool
        readSequence(self, Vec2f value) -> bool
        readSequence(self, Vec3f value) -> bool
        readSequence(self, Vec4f value) -> bool
        readSequence(self, Vec2d value) -> bool
        readSequence(self, Vec3d value) -> bool
        readSequence(self, Vec4d value) -> bool
        """
        return _osgDB.FieldReaderIterator_readSequence(self, *args)

FieldReaderIterator_swigregister = _osgDB.FieldReaderIterator_swigregister
FieldReaderIterator_swigregister(FieldReaderIterator)

class Input(FieldReaderIterator):
    """Proxy of C++ osgDB::Input class"""
    __swig_setmethods__ = {}
    for _s in [FieldReaderIterator]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Input, name, value)
    __swig_getmethods__ = {}
    for _s in [FieldReaderIterator]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Input, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> Input"""
        this = _osgDB.new_Input()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _osgDB.delete_Input
    __del__ = lambda self : None;
    def setOptions(self, *args):
        """setOptions(self, Options options)"""
        return _osgDB.Input_setOptions(self, *args)

    def getOptions(self):
        """getOptions(self) -> Options"""
        return _osgDB.Input_getOptions(self)

    def readObjectOfType(self, *args):
        """
        readObjectOfType(self, Object compObj) -> Object
        readObjectOfType(self, basic_type_wrapper btw) -> Object
        """
        return _osgDB.Input_readObjectOfType(self, *args)

    def readDrawable(self):
        """readDrawable(self) -> Drawable"""
        return _osgDB.Input_readDrawable(self)

    def readStateAttribute(self):
        """readStateAttribute(self) -> StateAttribute"""
        return _osgDB.Input_readStateAttribute(self)

    def readUniform(self):
        """readUniform(self) -> Uniform"""
        return _osgDB.Input_readUniform(self)

    def readObject(self, *args):
        """
        readObject(self) -> Object
        readObject(self, string fileName) -> Object
        """
        return _osgDB.Input_readObject(self, *args)

    def readImage(self, *args):
        """
        readImage(self) -> Image
        readImage(self, string fileName) -> Image
        """
        return _osgDB.Input_readImage(self, *args)

    def readNode(self, *args):
        """
        readNode(self) -> Node
        readNode(self, string fileName) -> Node
        """
        return _osgDB.Input_readNode(self, *args)

    def readShader(self, *args):
        """
        readShader(self) -> Shader
        readShader(self, string fileName) -> Shader
        """
        return _osgDB.Input_readShader(self, *args)

    def getObjectForUniqueID(self, *args):
        """getObjectForUniqueID(self, string uniqueID) -> Object"""
        return _osgDB.Input_getObjectForUniqueID(self, *args)

    def registerUniqueIDForObject(self, *args):
        """registerUniqueIDForObject(self, string uniqueID, Object obj)"""
        return _osgDB.Input_registerUniqueIDForObject(self, *args)

Input_swigregister = _osgDB.Input_swigregister
Input_swigregister(Input)

OSGDB_OUTPUT = _osgDB.OSGDB_OUTPUT
class Output(_object):
    """Proxy of C++ osgDB::Output class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Output, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Output, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> Output
        __init__(self, char name) -> Output
        """
        this = _osgDB.new_Output(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _osgDB.delete_Output
    __del__ = lambda self : None;
    def setOptions(self, *args):
        """setOptions(self, Options options)"""
        return _osgDB.Output_setOptions(self, *args)

    def getOptions(self):
        """getOptions(self) -> Options"""
        return _osgDB.Output_getOptions(self)

    def setWriteOutDefaultValues(self, *args):
        """setWriteOutDefaultValues(self, bool flag)"""
        return _osgDB.Output_setWriteOutDefaultValues(self, *args)

    def getWriteOutDefaultValues(self):
        """getWriteOutDefaultValues(self) -> bool"""
        return _osgDB.Output_getWriteOutDefaultValues(self)

    def open(self, *args):
        """open(self, char name)"""
        return _osgDB.Output_open(self, *args)

    def indent(self):
        """indent(self) -> Output"""
        return _osgDB.Output_indent(self)

    def wrapString(self, *args):
        """
        wrapString(self, char str) -> string
        wrapString(self, string str) -> string
        """
        return _osgDB.Output_wrapString(self, *args)

    def setIndentStep(self, *args):
        """setIndentStep(self, int step)"""
        return _osgDB.Output_setIndentStep(self, *args)

    def getIndentStep(self):
        """getIndentStep(self) -> int"""
        return _osgDB.Output_getIndentStep(self)

    def setIndent(self, *args):
        """setIndent(self, int indent)"""
        return _osgDB.Output_setIndent(self, *args)

    def getIndent(self):
        """getIndent(self) -> int"""
        return _osgDB.Output_getIndent(self)

    def setNumIndicesPerLine(self, *args):
        """setNumIndicesPerLine(self, int num)"""
        return _osgDB.Output_setNumIndicesPerLine(self, *args)

    def getNumIndicesPerLine(self):
        """getNumIndicesPerLine(self) -> int"""
        return _osgDB.Output_getNumIndicesPerLine(self)

    def moveIn(self):
        """moveIn(self)"""
        return _osgDB.Output_moveIn(self)

    def moveOut(self):
        """moveOut(self)"""
        return _osgDB.Output_moveOut(self)

    def writeObject(self, *args):
        """writeObject(self, Object obj) -> bool"""
        return _osgDB.Output_writeObject(self, *args)

    def writeBeginObject(self, *args):
        """writeBeginObject(self, string name)"""
        return _osgDB.Output_writeBeginObject(self, *args)

    def writeEndObject(self):
        """writeEndObject(self)"""
        return _osgDB.Output_writeEndObject(self)

    def writeUseID(self, *args):
        """writeUseID(self, string id)"""
        return _osgDB.Output_writeUseID(self, *args)

    def writeUniqueID(self, *args):
        """writeUniqueID(self, string id)"""
        return _osgDB.Output_writeUniqueID(self, *args)

    def getUniqueIDForObject(self, *args):
        """getUniqueIDForObject(self, Object obj, string uniqueID) -> bool"""
        return _osgDB.Output_getUniqueIDForObject(self, *args)

    def createUniqueIDForObject(self, *args):
        """createUniqueIDForObject(self, Object obj, string uniqueID) -> bool"""
        return _osgDB.Output_createUniqueIDForObject(self, *args)

    def registerUniqueIDForObject(self, *args):
        """registerUniqueIDForObject(self, Object obj, string uniqueID) -> bool"""
        return _osgDB.Output_registerUniqueIDForObject(self, *args)

    AS_IS = _osgDB.Output_AS_IS
    FULL_PATH = _osgDB.Output_FULL_PATH
    RELATIVE_PATH = _osgDB.Output_RELATIVE_PATH
    FILENAME_ONLY = _osgDB.Output_FILENAME_ONLY
    def setPathNameHint(self, *args):
        """setPathNameHint(self, PathNameHint pnh)"""
        return _osgDB.Output_setPathNameHint(self, *args)

    def getPathNameHint(self):
        """getPathNameHint(self) -> PathNameHint"""
        return _osgDB.Output_getPathNameHint(self)

    def getFileNameForOutput(self, *args):
        """getFileNameForOutput(self, string filename) -> string"""
        return _osgDB.Output_getFileNameForOutput(self, *args)

    def getFileName(self):
        """getFileName(self) -> string"""
        return _osgDB.Output_getFileName(self)

    def setOutputTextureFiles(self, *args):
        """setOutputTextureFiles(self, bool flag)"""
        return _osgDB.Output_setOutputTextureFiles(self, *args)

    def getOutputTextureFiles(self):
        """getOutputTextureFiles(self) -> bool"""
        return _osgDB.Output_getOutputTextureFiles(self)

    def getTextureFileNameForOutput(self):
        """getTextureFileNameForOutput(self) -> string"""
        return _osgDB.Output_getTextureFileNameForOutput(self)

    def setOutputShaderFiles(self, *args):
        """setOutputShaderFiles(self, bool flag)"""
        return _osgDB.Output_setOutputShaderFiles(self, *args)

    def getOutputShaderFiles(self):
        """getOutputShaderFiles(self) -> bool"""
        return _osgDB.Output_getOutputShaderFiles(self)

    def getShaderFileNameForOutput(self):
        """getShaderFileNameForOutput(self) -> string"""
        return _osgDB.Output_getShaderFileNameForOutput(self)

    def setExternalFileWritten(self, *args):
        """
        setExternalFileWritten(self, string filename, bool hasBeenWritten = True)
        setExternalFileWritten(self, string filename)
        """
        return _osgDB.Output_setExternalFileWritten(self, *args)

    def getExternalFileWritten(self, *args):
        """getExternalFileWritten(self, string filename) -> bool"""
        return _osgDB.Output_getExternalFileWritten(self, *args)

Output_swigregister = _osgDB.Output_swigregister
Output_swigregister(Output)

OSGDB_PARAMETEROUTPUT = _osgDB.OSGDB_PARAMETEROUTPUT
class ParameterOutput(_object):
    """Proxy of C++ osgDB::ParameterOutput class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ParameterOutput, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ParameterOutput, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, Output fw) -> ParameterOutput
        __init__(self, Output fw, int numItemsPerLine) -> ParameterOutput
        """
        this = _osgDB.new_ParameterOutput(*args)
        try: self.this.append(this)
        except: self.this = this
    def begin(self):
        """begin(self)"""
        return _osgDB.ParameterOutput_begin(self)

    def newLine(self):
        """newLine(self)"""
        return _osgDB.ParameterOutput_newLine(self)

    def end(self):
        """end(self)"""
        return _osgDB.ParameterOutput_end(self)

    __swig_destroy__ = _osgDB.delete_ParameterOutput
    __del__ = lambda self : None;
ParameterOutput_swigregister = _osgDB.ParameterOutput_swigregister
ParameterOutput_swigregister(ParameterOutput)

OSGDB_IMAGEOPTIONS = _osgDB.OSGDB_IMAGEOPTIONS
class ImageOptions(_object):
    """Proxy of C++ osgDB::ImageOptions class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ImageOptions, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ImageOptions, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> ImageOptions
        __init__(self, string str) -> ImageOptions
        __init__(self, ImageOptions options, CopyOp copyop = SHALLOW_COPY) -> ImageOptions
        __init__(self, ImageOptions options) -> ImageOptions
        """
        this = _osgDB.new_ImageOptions(*args)
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgDB.ImageOptions_cloneType(self)

    def clone(self, *args):
        """clone(self, CopyOp copyop) -> Object"""
        return _osgDB.ImageOptions_clone(self, *args)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgDB.ImageOptions_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgDB.ImageOptions_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgDB.ImageOptions_className(self)

    ALL_IMAGE = _osgDB.ImageOptions_ALL_IMAGE
    RATIO_WINDOW = _osgDB.ImageOptions_RATIO_WINDOW
    PIXEL_WINDOW = _osgDB.ImageOptions_PIXEL_WINDOW
    NEAREST = _osgDB.ImageOptions_NEAREST
    LINEAR = _osgDB.ImageOptions_LINEAR
    CUBIC = _osgDB.ImageOptions_CUBIC
    __swig_setmethods__["_destinationImage"] = _osgDB.ImageOptions__destinationImage_set
    __swig_getmethods__["_destinationImage"] = _osgDB.ImageOptions__destinationImage_get
    if _newclass:_destinationImage = _swig_property(_osgDB.ImageOptions__destinationImage_get, _osgDB.ImageOptions__destinationImage_set)
    __swig_setmethods__["_destinationDataType"] = _osgDB.ImageOptions__destinationDataType_set
    __swig_getmethods__["_destinationDataType"] = _osgDB.ImageOptions__destinationDataType_get
    if _newclass:_destinationDataType = _swig_property(_osgDB.ImageOptions__destinationDataType_get, _osgDB.ImageOptions__destinationDataType_set)
    __swig_setmethods__["_destinationPixelFormat"] = _osgDB.ImageOptions__destinationPixelFormat_set
    __swig_getmethods__["_destinationPixelFormat"] = _osgDB.ImageOptions__destinationPixelFormat_get
    if _newclass:_destinationPixelFormat = _swig_property(_osgDB.ImageOptions__destinationPixelFormat_get, _osgDB.ImageOptions__destinationPixelFormat_set)
    def init(self):
        """init(self)"""
        return _osgDB.ImageOptions_init(self)

    __swig_destroy__ = _osgDB.delete_ImageOptions
    __del__ = lambda self : None;
ImageOptions_swigregister = _osgDB.ImageOptions_swigregister
ImageOptions_swigregister(ImageOptions)

OSGDB_FILEUTILS = _osgDB.OSGDB_FILEUTILS

def fopen(*args):
  """fopen(char filename, char mode) -> FILE"""
  return _osgDB.fopen(*args)

def makeDirectory(*args):
  """makeDirectory(string directoryPath) -> bool"""
  return _osgDB.makeDirectory(*args)

def makeDirectoryForFile(*args):
  """makeDirectoryForFile(string filePath) -> bool"""
  return _osgDB.makeDirectoryForFile(*args)

def getCurrentWorkingDirectory():
  """getCurrentWorkingDirectory() -> string"""
  return _osgDB.getCurrentWorkingDirectory()

def setCurrentWorkingDirectory(*args):
  """setCurrentWorkingDirectory(string newCurrentWorkingDirectory) -> bool"""
  return _osgDB.setCurrentWorkingDirectory(*args)

def fileExists(*args):
  """fileExists(string filename) -> bool"""
  return _osgDB.fileExists(*args)
FILE_NOT_FOUND = _osgDB.FILE_NOT_FOUND
REGULAR_FILE = _osgDB.REGULAR_FILE
DIRECTORY = _osgDB.DIRECTORY

def fileType(*args):
  """fileType(string filename) -> FileType"""
  return _osgDB.fileType(*args)

def getDirectoryContents(*args):
  """getDirectoryContents(string dirName) -> DirectoryContents"""
  return _osgDB.getDirectoryContents(*args)

def expandWildcardsInFilename(*args):
  """expandWildcardsInFilename(string filename) -> DirectoryContents"""
  return _osgDB.expandWildcardsInFilename(*args)
OK = _osgDB.OK
SOURCE_EQUALS_DESTINATION = _osgDB.SOURCE_EQUALS_DESTINATION
BAD_ARGUMENT = _osgDB.BAD_ARGUMENT
SOURCE_MISSING = _osgDB.SOURCE_MISSING
SOURCE_NOT_OPENED = _osgDB.SOURCE_NOT_OPENED
DESTINATION_NOT_OPENED = _osgDB.DESTINATION_NOT_OPENED
READ_ERROR = _osgDB.READ_ERROR
WRITE_ERROR = _osgDB.WRITE_ERROR

def copyFile(*args):
  """copyFile(string source, string destination) -> Value"""
  return _osgDB.copyFile(*args)

def getDataFilePathList():
  """getDataFilePathList() -> FilePathList"""
  return _osgDB.getDataFilePathList()

def getLibraryFilePathList():
  """getLibraryFilePathList() -> FilePathList"""
  return _osgDB.getLibraryFilePathList()

def convertStringPathIntoFilePathList(*args):
  """convertStringPathIntoFilePathList(string paths, FilePathList filepath)"""
  return _osgDB.convertStringPathIntoFilePathList(*args)

def appendPlatformSpecificLibraryFilePaths(*args):
  """appendPlatformSpecificLibraryFilePaths(FilePathList filepath)"""
  return _osgDB.appendPlatformSpecificLibraryFilePaths(*args)

def appendPlatformSpecificResourceFilePaths(*args):
  """appendPlatformSpecificResourceFilePaths(FilePathList filepath)"""
  return _osgDB.appendPlatformSpecificResourceFilePaths(*args)
OSGDB_FILENAMEUTILS = _osgDB.OSGDB_FILENAMEUTILS

def getFilePath(*args):
  """getFilePath(string filename) -> string"""
  return _osgDB.getFilePath(*args)

def getFileExtension(*args):
  """getFileExtension(string filename) -> string"""
  return _osgDB.getFileExtension(*args)

def getFileExtensionIncludingDot(*args):
  """getFileExtensionIncludingDot(string filename) -> string"""
  return _osgDB.getFileExtensionIncludingDot(*args)

def getLowerCaseFileExtension(*args):
  """getLowerCaseFileExtension(string filename) -> string"""
  return _osgDB.getLowerCaseFileExtension(*args)

def getSimpleFileName(*args):
  """getSimpleFileName(string fileName) -> string"""
  return _osgDB.getSimpleFileName(*args)

def getNameLessExtension(*args):
  """getNameLessExtension(string fileName) -> string"""
  return _osgDB.getNameLessExtension(*args)

def getNameLessAllExtensions(*args):
  """getNameLessAllExtensions(string fileName) -> string"""
  return _osgDB.getNameLessAllExtensions(*args)

def getStrippedName(*args):
  """getStrippedName(string fileName) -> string"""
  return _osgDB.getStrippedName(*args)

def getPathRelative(*args):
  """getPathRelative(string _from, string to) -> string"""
  return _osgDB.getPathRelative(*args)

def getPathRoot(*args):
  """getPathRoot(string path) -> string"""
  return _osgDB.getPathRoot(*args)

def isAbsolutePath(*args):
  """isAbsolutePath(string path) -> bool"""
  return _osgDB.isAbsolutePath(*args)

def convertFileNameToWindowsStyle(*args):
  """convertFileNameToWindowsStyle(string fileName) -> string"""
  return _osgDB.convertFileNameToWindowsStyle(*args)

def convertFileNameToUnixStyle(*args):
  """convertFileNameToUnixStyle(string fileName) -> string"""
  return _osgDB.convertFileNameToUnixStyle(*args)

def convertToLowerCase(*args):
  """convertToLowerCase(string fileName) -> string"""
  return _osgDB.convertToLowerCase(*args)

def getNativePathSeparator():
  """getNativePathSeparator() -> char"""
  return _osgDB.getNativePathSeparator()

def isFileNameNativeStyle(*args):
  """isFileNameNativeStyle(string fileName) -> bool"""
  return _osgDB.isFileNameNativeStyle(*args)

def convertFileNameToNativeStyle(*args):
  """convertFileNameToNativeStyle(string fileName) -> string"""
  return _osgDB.convertFileNameToNativeStyle(*args)

def containsServerAddress(*args):
  """containsServerAddress(string filename) -> bool"""
  return _osgDB.containsServerAddress(*args)

def getServerProtocol(*args):
  """getServerProtocol(string filename) -> string"""
  return _osgDB.getServerProtocol(*args)

def getServerAddress(*args):
  """getServerAddress(string filename) -> string"""
  return _osgDB.getServerAddress(*args)

def getServerFileName(*args):
  """getServerFileName(string filename) -> string"""
  return _osgDB.getServerFileName(*args)

def concatPaths(*args):
  """concatPaths(string left, string right) -> string"""
  return _osgDB.concatPaths(*args)

def getRealPath(*args):
  """getRealPath(string path) -> string"""
  return _osgDB.getRealPath(*args)

def getPathElements(*args):
  """getPathElements(string path, __dummy_0__ out_elements)"""
  return _osgDB.getPathElements(*args)
OSGDB_DYNAMICLIBRARY = _osgDB.OSGDB_DYNAMICLIBRARY
class DynamicLibrary(osg.Referenced):
    """Proxy of C++ osgDB::DynamicLibrary class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DynamicLibrary, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, DynamicLibrary, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def loadLibrary(*args):
        """loadLibrary(string libraryName) -> DynamicLibrary"""
        return _osgDB.DynamicLibrary_loadLibrary(*args)

    if _newclass:loadLibrary = staticmethod(loadLibrary)
    __swig_getmethods__["loadLibrary"] = lambda x: loadLibrary
    def getName(self):
        """getName(self) -> string"""
        return _osgDB.DynamicLibrary_getName(self)

    def getFullName(self):
        """getFullName(self) -> string"""
        return _osgDB.DynamicLibrary_getFullName(self)

    def getHandle(self):
        """getHandle(self) -> HANDLE"""
        return _osgDB.DynamicLibrary_getHandle(self)

    def getProcAddress(self, *args):
        """getProcAddress(self, string procName) -> PROC_ADDRESS"""
        return _osgDB.DynamicLibrary_getProcAddress(self, *args)

DynamicLibrary_swigregister = _osgDB.DynamicLibrary_swigregister
DynamicLibrary_swigregister(DynamicLibrary)

def findFileInPath(*args):
  """
    findFileInPath(string filename, FilePathList filePath, CaseSensitivity caseSensitivity = CASE_SENSITIVE) -> string
    findFileInPath(string filename, FilePathList filePath) -> string
    """
  return _osgDB.findFileInPath(*args)

def findFileInDirectory(*args):
  """
    findFileInDirectory(string fileName, string dirName, CaseSensitivity caseSensitivity = CASE_SENSITIVE) -> string
    findFileInDirectory(string fileName, string dirName) -> string
    """
  return _osgDB.findFileInDirectory(*args)

def setDataFilePathList(*args):
  """
    setDataFilePathList(FilePathList filepath)
    setDataFilePathList(string paths)
    """
  return _osgDB.setDataFilePathList(*args)

def findDataFile(*args):
  """
    findDataFile(string filename, CaseSensitivity caseSensitivity = CASE_SENSITIVE) -> string
    findDataFile(string filename) -> string
    findDataFile(string filename, Options options, CaseSensitivity caseSensitivity = CASE_SENSITIVE) -> string
    findDataFile(string filename, Options options) -> string
    """
  return _osgDB.findDataFile(*args)

def setLibraryFilePathList(*args):
  """
    setLibraryFilePathList(FilePathList filepaths)
    setLibraryFilePathList(string paths)
    """
  return _osgDB.setLibraryFilePathList(*args)

def findLibraryFile(*args):
  """
    findLibraryFile(string filename, CaseSensitivity caseSensitivity = CASE_SENSITIVE) -> string
    findLibraryFile(string filename) -> string
    """
  return _osgDB.findLibraryFile(*args)
cvar = _osgDB.cvar
UNIX_PATH_SEPARATOR = cvar.UNIX_PATH_SEPARATOR
WINDOWS_PATH_SEPARATOR = cvar.WINDOWS_PATH_SEPARATOR

def equalCaseInsensitive(*args):
  """
    equalCaseInsensitive(string lhs, string rhs) -> bool
    equalCaseInsensitive(string lhs, char rhs) -> bool
    """
  return _osgDB.equalCaseInsensitive(*args)

def DynamicLibrary_loadLibrary(*args):
  """DynamicLibrary_loadLibrary(string libraryName) -> DynamicLibrary"""
  return _osgDB.DynamicLibrary_loadLibrary(*args)

OSGDB_DATABASEPAGER = _osgDB.OSGDB_DATABASEPAGER
class DatabasePager(_object):
    """Proxy of C++ osgDB::DatabasePager class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DatabasePager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DatabasePager, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DatabasePager
        __init__(self, DatabasePager rhs) -> DatabasePager
        """
        this = _osgDB.new_DatabasePager(*args)
        try: self.this.append(this)
        except: self.this = this
    def className(self):
        """className(self) -> char"""
        return _osgDB.DatabasePager_className(self)

    def clone(self):
        """clone(self) -> DatabasePager"""
        return _osgDB.DatabasePager_clone(self)

    def prototype():
        """prototype() -> osg::ref_ptr<(osgDB::DatabasePager)>"""
        return _osgDB.DatabasePager_prototype()

    if _newclass:prototype = staticmethod(prototype)
    __swig_getmethods__["prototype"] = lambda x: prototype
    def create():
        """create() -> DatabasePager"""
        return _osgDB.DatabasePager_create()

    if _newclass:create = staticmethod(create)
    __swig_getmethods__["create"] = lambda x: create
    def requestNodeFile(self, *args):
        """
        requestNodeFile(self, string fileName, NodePath nodePath, float priority, 
            FrameStamp framestamp, osg::ref_ptr<(osg::Referenced)> databaseRequest, 
            Referenced options)
        """
        return _osgDB.DatabasePager_requestNodeFile(self, *args)

    def setSchedulePriority(self, *args):
        """setSchedulePriority(self, OpenThreads::Thread::ThreadPriority priority) -> int"""
        return _osgDB.DatabasePager_setSchedulePriority(self, *args)

    def cancel(self):
        """cancel(self) -> int"""
        return _osgDB.DatabasePager_cancel(self)

    def isRunning(self):
        """isRunning(self) -> bool"""
        return _osgDB.DatabasePager_isRunning(self)

    def clear(self):
        """clear(self)"""
        return _osgDB.DatabasePager_clear(self)

    def setUpThreads(self, totalNumThreads = 2, numHttpThreads = 1):
        """
        setUpThreads(self, unsigned int totalNumThreads = 2, unsigned int numHttpThreads = 1)
        setUpThreads(self, unsigned int totalNumThreads = 2)
        setUpThreads(self)
        """
        return _osgDB.DatabasePager_setUpThreads(self, totalNumThreads, numHttpThreads)

    def setDatabasePagerThreadPause(self, *args):
        """setDatabasePagerThreadPause(self, bool pause)"""
        return _osgDB.DatabasePager_setDatabasePagerThreadPause(self, *args)

    def getDatabasePagerThreadPause(self):
        """getDatabasePagerThreadPause(self) -> bool"""
        return _osgDB.DatabasePager_getDatabasePagerThreadPause(self)

    def setAcceptNewDatabaseRequests(self, *args):
        """setAcceptNewDatabaseRequests(self, bool acceptNewRequests)"""
        return _osgDB.DatabasePager_setAcceptNewDatabaseRequests(self, *args)

    def getAcceptNewDatabaseRequests(self):
        """getAcceptNewDatabaseRequests(self) -> bool"""
        return _osgDB.DatabasePager_getAcceptNewDatabaseRequests(self)

    def getNumFramesActive(self):
        """getNumFramesActive(self) -> int"""
        return _osgDB.DatabasePager_getNumFramesActive(self)

    def signalBeginFrame(self, *args):
        """signalBeginFrame(self, FrameStamp framestamp)"""
        return _osgDB.DatabasePager_signalBeginFrame(self, *args)

    def signalEndFrame(self):
        """signalEndFrame(self)"""
        return _osgDB.DatabasePager_signalEndFrame(self)

    def registerPagedLODs(self, *args):
        """
        registerPagedLODs(self, Node subgraph, unsigned int frameNumber = 0)
        registerPagedLODs(self, Node subgraph)
        """
        return _osgDB.DatabasePager_registerPagedLODs(self, *args)

    def setIncrementalCompileOperation(self, *args):
        """setIncrementalCompileOperation(self, osgUtil::IncrementalCompileOperation ico)"""
        return _osgDB.DatabasePager_setIncrementalCompileOperation(self, *args)

    def getIncrementalCompileOperation(self):
        """getIncrementalCompileOperation(self) -> osgUtil::IncrementalCompileOperation"""
        return _osgDB.DatabasePager_getIncrementalCompileOperation(self)

    def setDoPreCompile(self, *args):
        """setDoPreCompile(self, bool flag)"""
        return _osgDB.DatabasePager_setDoPreCompile(self, *args)

    def getDoPreCompile(self):
        """getDoPreCompile(self) -> bool"""
        return _osgDB.DatabasePager_getDoPreCompile(self)

    def setTargetMaximumNumberOfPageLOD(self, *args):
        """setTargetMaximumNumberOfPageLOD(self, unsigned int target)"""
        return _osgDB.DatabasePager_setTargetMaximumNumberOfPageLOD(self, *args)

    def getTargetMaximumNumberOfPageLOD(self):
        """getTargetMaximumNumberOfPageLOD(self) -> unsigned int"""
        return _osgDB.DatabasePager_getTargetMaximumNumberOfPageLOD(self)

    def setDeleteRemovedSubgraphsInDatabaseThread(self, *args):
        """setDeleteRemovedSubgraphsInDatabaseThread(self, bool flag)"""
        return _osgDB.DatabasePager_setDeleteRemovedSubgraphsInDatabaseThread(self, *args)

    def getDeleteRemovedSubgraphsInDatabaseThread(self):
        """getDeleteRemovedSubgraphsInDatabaseThread(self) -> bool"""
        return _osgDB.DatabasePager_getDeleteRemovedSubgraphsInDatabaseThread(self)

    DO_NOT_MODIFY_DRAWABLE_SETTINGS = _osgDB.DatabasePager_DO_NOT_MODIFY_DRAWABLE_SETTINGS
    USE_DISPLAY_LISTS = _osgDB.DatabasePager_USE_DISPLAY_LISTS
    USE_VERTEX_BUFFER_OBJECTS = _osgDB.DatabasePager_USE_VERTEX_BUFFER_OBJECTS
    USE_VERTEX_ARRAYS = _osgDB.DatabasePager_USE_VERTEX_ARRAYS
    def setDrawablePolicy(self, *args):
        """setDrawablePolicy(self, DrawablePolicy policy)"""
        return _osgDB.DatabasePager_setDrawablePolicy(self, *args)

    def getDrawablePolicy(self):
        """getDrawablePolicy(self) -> DrawablePolicy"""
        return _osgDB.DatabasePager_getDrawablePolicy(self)

    def setApplyPBOToImages(self, *args):
        """setApplyPBOToImages(self, bool assignPBOToImages)"""
        return _osgDB.DatabasePager_setApplyPBOToImages(self, *args)

    def getApplyPBOToImages(self):
        """getApplyPBOToImages(self) -> bool"""
        return _osgDB.DatabasePager_getApplyPBOToImages(self)

    def setUnrefImageDataAfterApplyPolicy(self, *args):
        """setUnrefImageDataAfterApplyPolicy(self, bool changeAutoUnRef, bool valueAutoUnRef)"""
        return _osgDB.DatabasePager_setUnrefImageDataAfterApplyPolicy(self, *args)

    def getUnrefImageDataAfterApplyPolicy(self, *args):
        """getUnrefImageDataAfterApplyPolicy(self, bool changeAutoUnRef, bool valueAutoUnRef)"""
        return _osgDB.DatabasePager_getUnrefImageDataAfterApplyPolicy(self, *args)

    def setMaxAnisotropyPolicy(self, *args):
        """setMaxAnisotropyPolicy(self, bool changeAnisotropy, float valueAnisotropy)"""
        return _osgDB.DatabasePager_setMaxAnisotropyPolicy(self, *args)

    def getMaxAnisotropyPolicy(self, *args):
        """getMaxAnisotropyPolicy(self, bool changeAnisotropy, float valueAnisotropy)"""
        return _osgDB.DatabasePager_getMaxAnisotropyPolicy(self, *args)

    def requiresUpdateSceneGraph(self):
        """requiresUpdateSceneGraph(self) -> bool"""
        return _osgDB.DatabasePager_requiresUpdateSceneGraph(self)

    def updateSceneGraph(self, *args):
        """updateSceneGraph(self, FrameStamp frameStamp)"""
        return _osgDB.DatabasePager_updateSceneGraph(self, *args)

    def getFileRequestListSize(self):
        """getFileRequestListSize(self) -> unsigned int"""
        return _osgDB.DatabasePager_getFileRequestListSize(self)

    def getDataToCompileListSize(self):
        """getDataToCompileListSize(self) -> unsigned int"""
        return _osgDB.DatabasePager_getDataToCompileListSize(self)

    def getDataToMergeListSize(self):
        """getDataToMergeListSize(self) -> unsigned int"""
        return _osgDB.DatabasePager_getDataToMergeListSize(self)

    def getRequestsInProgress(self):
        """getRequestsInProgress(self) -> bool"""
        return _osgDB.DatabasePager_getRequestsInProgress(self)

    def getMinimumTimeToMergeTile(self):
        """getMinimumTimeToMergeTile(self) -> double"""
        return _osgDB.DatabasePager_getMinimumTimeToMergeTile(self)

    def getMaximumTimeToMergeTile(self):
        """getMaximumTimeToMergeTile(self) -> double"""
        return _osgDB.DatabasePager_getMaximumTimeToMergeTile(self)

    def getAverageTimeToMergeTiles(self):
        """getAverageTimeToMergeTiles(self) -> double"""
        return _osgDB.DatabasePager_getAverageTimeToMergeTiles(self)

    def resetStats(self):
        """resetStats(self)"""
        return _osgDB.DatabasePager_resetStats(self)

DatabasePager_swigregister = _osgDB.DatabasePager_swigregister
DatabasePager_swigregister(DatabasePager)

def DatabasePager_prototype():
  """DatabasePager_prototype() -> osg::ref_ptr<(osgDB::DatabasePager)>"""
  return _osgDB.DatabasePager_prototype()

def DatabasePager_create():
  """DatabasePager_create() -> DatabasePager"""
  return _osgDB.DatabasePager_create()

OSGDB_ARCHIVE = _osgDB.OSGDB_ARCHIVE
class Archive(_object):
    """Proxy of C++ osgDB::Archive class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Archive, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Archive, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _osgDB.delete_Archive
    __del__ = lambda self : None;
    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgDB.Archive_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgDB.Archive_className(self)

    def acceptsExtension(self, *args):
        """acceptsExtension(self, string arg0) -> bool"""
        return _osgDB.Archive_acceptsExtension(self, *args)

    def close(self):
        """close(self)"""
        return _osgDB.Archive_close(self)

    def getArchiveFileName(self):
        """getArchiveFileName(self) -> string"""
        return _osgDB.Archive_getArchiveFileName(self)

    def getMasterFileName(self):
        """getMasterFileName(self) -> string"""
        return _osgDB.Archive_getMasterFileName(self)

    def fileExists(self, *args):
        """fileExists(self, string filename) -> bool"""
        return _osgDB.Archive_fileExists(self, *args)

    def getFileType(self, *args):
        """getFileType(self, string filename) -> FileType"""
        return _osgDB.Archive_getFileType(self, *args)

    def getFileNames(self, *args):
        """getFileNames(self, FileNameList fileNames) -> bool"""
        return _osgDB.Archive_getFileNames(self, *args)

    def getDirectoryContents(self, *args):
        """getDirectoryContents(self, string dirName) -> DirectoryContents"""
        return _osgDB.Archive_getDirectoryContents(self, *args)

    def readShader(self, *args):
        """
        readShader(self, string arg0, Options arg1 = None) -> ReadResult
        readShader(self, string arg0) -> ReadResult
        """
        return _osgDB.Archive_readShader(self, *args)

    def writeShader(self, *args):
        """
        writeShader(self, Shader arg0, string arg1, Options arg2 = None) -> WriteResult
        writeShader(self, Shader arg0, string arg1) -> WriteResult
        """
        return _osgDB.Archive_writeShader(self, *args)

Archive_swigregister = _osgDB.Archive_swigregister
Archive_swigregister(Archive)

OSGDB_DOTOSGWRAPPER = _osgDB.OSGDB_DOTOSGWRAPPER
class DotOsgWrapper(osg.Referenced):
    """Proxy of C++ osgDB::DotOsgWrapper class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DotOsgWrapper, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, DotOsgWrapper, name)
    __repr__ = _swig_repr
    READ_AND_WRITE = _osgDB.DotOsgWrapper_READ_AND_WRITE
    READ_ONLY = _osgDB.DotOsgWrapper_READ_ONLY
    def __init__(self, *args): 
        """
        __init__(self, Object proto, string name, string associates, ReadFunc readFunc, 
            WriteFunc writeFunc, ReadWriteMode readWriteMode = READ_AND_WRITE) -> DotOsgWrapper
        __init__(self, Object proto, string name, string associates, ReadFunc readFunc, 
            WriteFunc writeFunc) -> DotOsgWrapper
        """
        this = _osgDB.new_DotOsgWrapper(*args)
        try: self.this.append(this)
        except: self.this = this
    def getPrototype(self):
        """getPrototype(self) -> Object"""
        return _osgDB.DotOsgWrapper_getPrototype(self)

    def getName(self):
        """getName(self) -> string"""
        return _osgDB.DotOsgWrapper_getName(self)

    def getAssociates(self):
        """getAssociates(self) -> Associates"""
        return _osgDB.DotOsgWrapper_getAssociates(self)

    def getReadFunc(self):
        """getReadFunc(self) -> ReadFunc"""
        return _osgDB.DotOsgWrapper_getReadFunc(self)

    def getWriteFunc(self):
        """getWriteFunc(self) -> WriteFunc"""
        return _osgDB.DotOsgWrapper_getWriteFunc(self)

    def getReadWriteMode(self):
        """getReadWriteMode(self) -> ReadWriteMode"""
        return _osgDB.DotOsgWrapper_getReadWriteMode(self)

DotOsgWrapper_swigregister = _osgDB.DotOsgWrapper_swigregister
DotOsgWrapper_swigregister(DotOsgWrapper)

def openArchive(*args):
  """
    openArchive(string filename, ArchiveStatus status, unsigned int indexBlockSizeHint = 4096) -> Archive
    openArchive(string filename, ArchiveStatus status) -> Archive
    openArchive(string filename, ArchiveStatus status, unsigned int indexBlockSizeHint, 
        Options options) -> Archive
    """
  return _osgDB.openArchive(*args)

class DeprecatedDotOsgWrapperManager(osg.Referenced):
    """Proxy of C++ osgDB::DeprecatedDotOsgWrapperManager class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DeprecatedDotOsgWrapperManager, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, DeprecatedDotOsgWrapperManager, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> DeprecatedDotOsgWrapperManager"""
        this = _osgDB.new_DeprecatedDotOsgWrapperManager()
        try: self.this.append(this)
        except: self.this = this
    def addDotOsgWrapper(self, *args):
        """addDotOsgWrapper(self, DotOsgWrapper wrapper)"""
        return _osgDB.DeprecatedDotOsgWrapperManager_addDotOsgWrapper(self, *args)

    def removeDotOsgWrapper(self, *args):
        """removeDotOsgWrapper(self, DotOsgWrapper wrapper)"""
        return _osgDB.DeprecatedDotOsgWrapperManager_removeDotOsgWrapper(self, *args)

    def readObjectOfType(self, *args):
        """
        readObjectOfType(self, Object compObj, Input fr) -> Object
        readObjectOfType(self, basic_type_wrapper btw, Input fr) -> Object
        """
        return _osgDB.DeprecatedDotOsgWrapperManager_readObjectOfType(self, *args)

    def readObject(self, *args):
        """readObject(self, Input fr) -> Object"""
        return _osgDB.DeprecatedDotOsgWrapperManager_readObject(self, *args)

    def readImage(self, *args):
        """readImage(self, Input fr) -> Image"""
        return _osgDB.DeprecatedDotOsgWrapperManager_readImage(self, *args)

    def readDrawable(self, *args):
        """readDrawable(self, Input fr) -> Drawable"""
        return _osgDB.DeprecatedDotOsgWrapperManager_readDrawable(self, *args)

    def readUniform(self, *args):
        """readUniform(self, Input fr) -> Uniform"""
        return _osgDB.DeprecatedDotOsgWrapperManager_readUniform(self, *args)

    def readStateAttribute(self, *args):
        """readStateAttribute(self, Input fr) -> StateAttribute"""
        return _osgDB.DeprecatedDotOsgWrapperManager_readStateAttribute(self, *args)

    def readNode(self, *args):
        """readNode(self, Input fr) -> Node"""
        return _osgDB.DeprecatedDotOsgWrapperManager_readNode(self, *args)

    def readShader(self, *args):
        """readShader(self, Input fr) -> Shader"""
        return _osgDB.DeprecatedDotOsgWrapperManager_readShader(self, *args)

    def writeObject(self, *args):
        """writeObject(self, Object obj, Output fw) -> bool"""
        return _osgDB.DeprecatedDotOsgWrapperManager_writeObject(self, *args)

    def getLibraryFileNamesToTry(self, *args):
        """getLibraryFileNamesToTry(self, string name, FileNames fileNames) -> bool"""
        return _osgDB.DeprecatedDotOsgWrapperManager_getLibraryFileNamesToTry(self, *args)

DeprecatedDotOsgWrapperManager_swigregister = _osgDB.DeprecatedDotOsgWrapperManager_swigregister
DeprecatedDotOsgWrapperManager_swigregister(DeprecatedDotOsgWrapperManager)

class RegisterDotOsgWrapperProxy(_object):
    """Proxy of C++ osgDB::RegisterDotOsgWrapperProxy class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RegisterDotOsgWrapperProxy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RegisterDotOsgWrapperProxy, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self, Object proto, string name, string associates, ReadFunc readFunc, 
            WriteFunc writeFunc, ReadWriteMode readWriteMode = READ_AND_WRITE) -> RegisterDotOsgWrapperProxy
        __init__(self, Object proto, string name, string associates, ReadFunc readFunc, 
            WriteFunc writeFunc) -> RegisterDotOsgWrapperProxy
        """
        this = _osgDB.new_RegisterDotOsgWrapperProxy(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _osgDB.delete_RegisterDotOsgWrapperProxy
    __del__ = lambda self : None;
RegisterDotOsgWrapperProxy_swigregister = _osgDB.RegisterDotOsgWrapperProxy_swigregister
RegisterDotOsgWrapperProxy_swigregister(RegisterDotOsgWrapperProxy)

OSGDB_REGISTRY = _osgDB.OSGDB_REGISTRY
class basic_type_wrapper(_object):
    """Proxy of C++ osgDB::basic_type_wrapper class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, basic_type_wrapper, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, basic_type_wrapper, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _osgDB.delete_basic_type_wrapper
    __del__ = lambda self : None;
    def matches(self, *args):
        """matches(self, Object proto) -> bool"""
        return _osgDB.basic_type_wrapper_matches(self, *args)

basic_type_wrapper_swigregister = _osgDB.basic_type_wrapper_swigregister
basic_type_wrapper_swigregister(basic_type_wrapper)

class Registry(osg.Referenced):
    """Proxy of C++ osgDB::Registry class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Registry, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Registry, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def instance(erase = False):
        """
        instance(bool erase = False) -> Registry
        instance() -> Registry
        """
        return _osgDB.Registry_instance(erase)

    if _newclass:instance = staticmethod(instance)
    __swig_getmethods__["instance"] = lambda x: instance
    def readCommandLine(self, *args):
        """readCommandLine(self, ArgumentParser commandLine)"""
        return _osgDB.Registry_readCommandLine(self, *args)

    def addFileExtensionAlias(self, *args):
        """addFileExtensionAlias(self, string mapExt, string toExt)"""
        return _osgDB.Registry_addFileExtensionAlias(self, *args)

    def readPluginAliasConfigurationFile(self, *args):
        """readPluginAliasConfigurationFile(self, string file) -> bool"""
        return _osgDB.Registry_readPluginAliasConfigurationFile(self, *args)

    def addMimeTypeExtensionMapping(self, *args):
        """addMimeTypeExtensionMapping(self, string fromMimeType, string toExt)"""
        return _osgDB.Registry_addMimeTypeExtensionMapping(self, *args)

    def addReaderWriter(self, *args):
        """addReaderWriter(self,  rw)"""
        return _osgDB.Registry_addReaderWriter(self, *args)

    def removeReaderWriter(self, *args):
        """removeReaderWriter(self,  rw)"""
        return _osgDB.Registry_removeReaderWriter(self, *args)

    def addImageProcessor(self, *args):
        """addImageProcessor(self, ImageProcessor ip)"""
        return _osgDB.Registry_addImageProcessor(self, *args)

    def removeImageProcessor(self, *args):
        """removeImageProcessor(self, ImageProcessor ip)"""
        return _osgDB.Registry_removeImageProcessor(self, *args)

    def createLibraryNameForFile(self, *args):
        """createLibraryNameForFile(self, string fileName) -> string"""
        return _osgDB.Registry_createLibraryNameForFile(self, *args)

    def createLibraryNameForExtension(self, *args):
        """createLibraryNameForExtension(self, string ext) -> string"""
        return _osgDB.Registry_createLibraryNameForExtension(self, *args)

    def createLibraryNameForNodeKit(self, *args):
        """createLibraryNameForNodeKit(self, string name) -> string"""
        return _osgDB.Registry_createLibraryNameForNodeKit(self, *args)

    NOT_LOADED = _osgDB.Registry_NOT_LOADED
    PREVIOUSLY_LOADED = _osgDB.Registry_PREVIOUSLY_LOADED
    LOADED = _osgDB.Registry_LOADED
    def loadLibrary(self, *args):
        """loadLibrary(self, string fileName) -> LoadStatus"""
        return _osgDB.Registry_loadLibrary(self, *args)

    def closeLibrary(self, *args):
        """closeLibrary(self, string fileName) -> bool"""
        return _osgDB.Registry_closeLibrary(self, *args)

    def closeAllLibraries(self):
        """closeAllLibraries(self)"""
        return _osgDB.Registry_closeAllLibraries(self)

    def getReaderWriterForExtension(self, *args):
        """getReaderWriterForExtension(self, string ext)"""
        return _osgDB.Registry_getReaderWriterForExtension(self, *args)

    def getReaderWriterForMimeType(self, *args):
        """getReaderWriterForMimeType(self, string mimeType)"""
        return _osgDB.Registry_getReaderWriterForMimeType(self, *args)

    def getReaderWriterList(self, *args):
        """
        getReaderWriterList(self) -> ReaderWriterList
        getReaderWriterList(self) -> ReaderWriterList
        """
        return _osgDB.Registry_getReaderWriterList(self, *args)

    def getImageProcessor(self):
        """getImageProcessor(self) -> ImageProcessor"""
        return _osgDB.Registry_getImageProcessor(self)

    def getImageProcessorForExtension(self, *args):
        """getImageProcessorForExtension(self, string ext) -> ImageProcessor"""
        return _osgDB.Registry_getImageProcessorForExtension(self, *args)

    def getImageProcessorList(self, *args):
        """
        getImageProcessorList(self) -> ImageProcessorList
        getImageProcessorList(self) -> ImageProcessorList
        """
        return _osgDB.Registry_getImageProcessorList(self, *args)

    def setFindFileCallback(self, *args):
        """setFindFileCallback(self, FindFileCallback cb)"""
        return _osgDB.Registry_setFindFileCallback(self, *args)

    def getFindFileCallback(self, *args):
        """
        getFindFileCallback(self) -> FindFileCallback
        getFindFileCallback(self) -> FindFileCallback
        """
        return _osgDB.Registry_getFindFileCallback(self, *args)

    def findDataFile(self, *args):
        """findDataFile(self, string fileName, Options options, CaseSensitivity caseSensitivity) -> string"""
        return _osgDB.Registry_findDataFile(self, *args)

    def findDataFileImplementation(self, *args):
        """findDataFileImplementation(self, string fileName, Options options, CaseSensitivity caseSensitivity) -> string"""
        return _osgDB.Registry_findDataFileImplementation(self, *args)

    def findLibraryFile(self, *args):
        """findLibraryFile(self, string fileName, Options options, CaseSensitivity caseSensitivity) -> string"""
        return _osgDB.Registry_findLibraryFile(self, *args)

    def findLibraryFileImplementation(self, *args):
        """findLibraryFileImplementation(self, string fileName, Options options, CaseSensitivity caseSensitivity) -> string"""
        return _osgDB.Registry_findLibraryFileImplementation(self, *args)

    def openArchive(self, *args):
        """
        openArchive(self, string fileName, ArchiveStatus status, unsigned int indexBlockSizeHint, 
            Options options) -> ReadResult
        """
        return _osgDB.Registry_openArchive(self, *args)

    def openArchiveImplementation(self, *args):
        """
        openArchiveImplementation(self, string fileName, ArchiveStatus status, unsigned int indexBlockSizeHint, 
            Options options) -> ReadResult
        """
        return _osgDB.Registry_openArchiveImplementation(self, *args)

    def readObject(self, *args):
        """
        readObject(self, string fileName, Options options, bool buildKdTreeIfRequired = True) -> ReadResult
        readObject(self, string fileName, Options options) -> ReadResult
        """
        return _osgDB.Registry_readObject(self, *args)

    def readObjectImplementation(self, *args):
        """readObjectImplementation(self, string fileName, Options options) -> ReadResult"""
        return _osgDB.Registry_readObjectImplementation(self, *args)

    def readImage(self, *args):
        """readImage(self, string fileName, Options options) -> ReadResult"""
        return _osgDB.Registry_readImage(self, *args)

    def readImageImplementation(self, *args):
        """readImageImplementation(self, string fileName, Options options) -> ReadResult"""
        return _osgDB.Registry_readImageImplementation(self, *args)

    def readHeightField(self, *args):
        """readHeightField(self, string fileName, Options options) -> ReadResult"""
        return _osgDB.Registry_readHeightField(self, *args)

    def readHeightFieldImplementation(self, *args):
        """readHeightFieldImplementation(self, string fileName, Options options) -> ReadResult"""
        return _osgDB.Registry_readHeightFieldImplementation(self, *args)

    def readNode(self, *args):
        """
        readNode(self, string fileName, Options options, bool buildKdTreeIfRequired = True) -> ReadResult
        readNode(self, string fileName, Options options) -> ReadResult
        """
        return _osgDB.Registry_readNode(self, *args)

    def readNodeImplementation(self, *args):
        """readNodeImplementation(self, string fileName, Options options) -> ReadResult"""
        return _osgDB.Registry_readNodeImplementation(self, *args)

    def readShader(self, *args):
        """readShader(self, string fileName, Options options) -> ReadResult"""
        return _osgDB.Registry_readShader(self, *args)

    def readShaderImplementation(self, *args):
        """readShaderImplementation(self, string fileName, Options options) -> ReadResult"""
        return _osgDB.Registry_readShaderImplementation(self, *args)

    def writeObject(self, *args):
        """writeObject(self, Object obj, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeObject(self, *args)

    def writeObjectImplementation(self, *args):
        """writeObjectImplementation(self, Object obj, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeObjectImplementation(self, *args)

    def writeImage(self, *args):
        """writeImage(self, Image obj, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeImage(self, *args)

    def writeImageImplementation(self, *args):
        """writeImageImplementation(self, Image obj, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeImageImplementation(self, *args)

    def writeHeightField(self, *args):
        """writeHeightField(self, HeightField obj, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeHeightField(self, *args)

    def writeHeightFieldImplementation(self, *args):
        """writeHeightFieldImplementation(self, HeightField obj, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeHeightFieldImplementation(self, *args)

    def writeNode(self, *args):
        """writeNode(self, Node node, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeNode(self, *args)

    def writeNodeImplementation(self, *args):
        """writeNodeImplementation(self, Node node, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeNodeImplementation(self, *args)

    def writeShader(self, *args):
        """writeShader(self, Shader obj, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeShader(self, *args)

    def writeShaderImplementation(self, *args):
        """writeShaderImplementation(self, Shader obj, string fileName, Options options) -> WriteResult"""
        return _osgDB.Registry_writeShaderImplementation(self, *args)

    def _buildKdTreeIfRequired(self, *args):
        """_buildKdTreeIfRequired(self, ReadResult result, Options options)"""
        return _osgDB.Registry__buildKdTreeIfRequired(self, *args)

    def setFileLocationCallback(self, *args):
        """setFileLocationCallback(self, FileLocationCallback cb)"""
        return _osgDB.Registry_setFileLocationCallback(self, *args)

    def getFileLocationCallback(self):
        """getFileLocationCallback(self) -> FileLocationCallback"""
        return _osgDB.Registry_getFileLocationCallback(self)

    def setBuildKdTreesHint(self, *args):
        """setBuildKdTreesHint(self, osgDB::Options::BuildKdTreesHint hint)"""
        return _osgDB.Registry_setBuildKdTreesHint(self, *args)

    def getBuildKdTreesHint(self):
        """getBuildKdTreesHint(self) -> osgDB::Options::BuildKdTreesHint"""
        return _osgDB.Registry_getBuildKdTreesHint(self)

    def setKdTreeBuilder(self, *args):
        """setKdTreeBuilder(self, osg::KdTreeBuilder builder)"""
        return _osgDB.Registry_setKdTreeBuilder(self, *args)

    def getKdTreeBuilder(self):
        """getKdTreeBuilder(self) -> osg::KdTreeBuilder"""
        return _osgDB.Registry_getKdTreeBuilder(self)

    def setFileCache(self, *args):
        """setFileCache(self, FileCache fileCache)"""
        return _osgDB.Registry_setFileCache(self, *args)

    def getFileCache(self, *args):
        """
        getFileCache(self) -> FileCache
        getFileCache(self) -> FileCache
        """
        return _osgDB.Registry_getFileCache(self, *args)

    def setAuthenticationMap(self, *args):
        """setAuthenticationMap(self, AuthenticationMap authenticationMap)"""
        return _osgDB.Registry_setAuthenticationMap(self, *args)

    def getAuthenticationMap(self, *args):
        """
        getAuthenticationMap(self) -> AuthenticationMap
        getAuthenticationMap(self) -> AuthenticationMap
        """
        return _osgDB.Registry_getAuthenticationMap(self, *args)

    def setCreateNodeFromImage(self, *args):
        """setCreateNodeFromImage(self, bool flag)"""
        return _osgDB.Registry_setCreateNodeFromImage(self, *args)

    def getCreateNodeFromImage(self):
        """getCreateNodeFromImage(self) -> bool"""
        return _osgDB.Registry_getCreateNodeFromImage(self)

    def setOptions(self, *args):
        """setOptions(self, Options opt)"""
        return _osgDB.Registry_setOptions(self, *args)

    def getOptions(self, *args):
        """
        getOptions(self) -> Options
        getOptions(self) -> Options
        """
        return _osgDB.Registry_getOptions(self, *args)

    def initFilePathLists(self):
        """initFilePathLists(self)"""
        return _osgDB.Registry_initFilePathLists(self)

    def initDataFilePathList(self):
        """initDataFilePathList(self)"""
        return _osgDB.Registry_initDataFilePathList(self)

    def setDataFilePathList(self, *args):
        """
        setDataFilePathList(self, FilePathList filepath)
        setDataFilePathList(self, string paths)
        """
        return _osgDB.Registry_setDataFilePathList(self, *args)

    def getDataFilePathList(self, *args):
        """
        getDataFilePathList(self) -> FilePathList
        getDataFilePathList(self) -> FilePathList
        """
        return _osgDB.Registry_getDataFilePathList(self, *args)

    def initLibraryFilePathList(self):
        """initLibraryFilePathList(self)"""
        return _osgDB.Registry_initLibraryFilePathList(self)

    def setLibraryFilePathList(self, *args):
        """
        setLibraryFilePathList(self, FilePathList filepath)
        setLibraryFilePathList(self, string paths)
        """
        return _osgDB.Registry_setLibraryFilePathList(self, *args)

    def getLibraryFilePathList(self, *args):
        """
        getLibraryFilePathList(self) -> FilePathList
        getLibraryFilePathList(self) -> FilePathList
        """
        return _osgDB.Registry_getLibraryFilePathList(self, *args)

    def updateTimeStampOfObjectsInCacheWithExternalReferences(self, *args):
        """updateTimeStampOfObjectsInCacheWithExternalReferences(self, FrameStamp frameStamp)"""
        return _osgDB.Registry_updateTimeStampOfObjectsInCacheWithExternalReferences(self, *args)

    def removeExpiredObjectsInCache(self, *args):
        """removeExpiredObjectsInCache(self, FrameStamp frameStamp)"""
        return _osgDB.Registry_removeExpiredObjectsInCache(self, *args)

    def setExpiryDelay(self, *args):
        """setExpiryDelay(self, double expiryDelay)"""
        return _osgDB.Registry_setExpiryDelay(self, *args)

    def getExpiryDelay(self):
        """getExpiryDelay(self) -> double"""
        return _osgDB.Registry_getExpiryDelay(self)

    def clearObjectCache(self):
        """clearObjectCache(self)"""
        return _osgDB.Registry_clearObjectCache(self)

    def addEntryToObjectCache(self, *args):
        """
        addEntryToObjectCache(self, string filename, Object object, double timestamp = 0.0)
        addEntryToObjectCache(self, string filename, Object object)
        """
        return _osgDB.Registry_addEntryToObjectCache(self, *args)

    def getFromObjectCache(self, *args):
        """getFromObjectCache(self, string fileName) -> Object"""
        return _osgDB.Registry_getFromObjectCache(self, *args)

    def getRefFromObjectCache(self, *args):
        """getRefFromObjectCache(self, string fileName) -> osg::ref_ptr<(osg::Object)>"""
        return _osgDB.Registry_getRefFromObjectCache(self, *args)

    def addToArchiveCache(self, *args):
        """addToArchiveCache(self, string fileName, Archive archive)"""
        return _osgDB.Registry_addToArchiveCache(self, *args)

    def removeFromArchiveCache(self, *args):
        """removeFromArchiveCache(self, string fileName)"""
        return _osgDB.Registry_removeFromArchiveCache(self, *args)

    def getFromArchiveCache(self, *args):
        """getFromArchiveCache(self, string fileName) -> Archive"""
        return _osgDB.Registry_getFromArchiveCache(self, *args)

    def getRefFromArchiveCache(self, *args):
        """getRefFromArchiveCache(self, string fileName) -> osg::ref_ptr<(osgDB::Archive)>"""
        return _osgDB.Registry_getRefFromArchiveCache(self, *args)

    def clearArchiveCache(self):
        """clearArchiveCache(self)"""
        return _osgDB.Registry_clearArchiveCache(self)

    def releaseGLObjects(self, state = None):
        """
        releaseGLObjects(self, State state = None)
        releaseGLObjects(self)
        """
        return _osgDB.Registry_releaseGLObjects(self, state)

    def getLibrary(self, *args):
        """getLibrary(self, string fileName) -> DynamicLibrary"""
        return _osgDB.Registry_getLibrary(self, *args)

    def setSharedStateManager(self, *args):
        """setSharedStateManager(self, SharedStateManager SharedStateManager)"""
        return _osgDB.Registry_setSharedStateManager(self, *args)

    def getOrCreateSharedStateManager(self):
        """getOrCreateSharedStateManager(self) -> SharedStateManager"""
        return _osgDB.Registry_getOrCreateSharedStateManager(self)

    def getSharedStateManager(self):
        """getSharedStateManager(self) -> SharedStateManager"""
        return _osgDB.Registry_getSharedStateManager(self)

    def addArchiveExtension(self, *args):
        """addArchiveExtension(self, string ext)"""
        return _osgDB.Registry_addArchiveExtension(self, *args)

    def registerProtocol(self, *args):
        """registerProtocol(self, string protocol)"""
        return _osgDB.Registry_registerProtocol(self, *args)

    def isProtocolRegistered(self, *args):
        """isProtocolRegistered(self, string protocol) -> bool"""
        return _osgDB.Registry_isProtocolRegistered(self, *args)

    def getObjectWrapperManager(self):
        """getObjectWrapperManager(self) -> ObjectWrapperManager"""
        return _osgDB.Registry_getObjectWrapperManager(self)

    def getDeprecatedDotOsgObjectWrapperManager(self):
        """getDeprecatedDotOsgObjectWrapperManager(self) -> DeprecatedDotOsgWrapperManager"""
        return _osgDB.Registry_getDeprecatedDotOsgObjectWrapperManager(self)

    def getArchiveExtensions(self):
        """getArchiveExtensions(self) -> ArchiveExtensionList"""
        return _osgDB.Registry_getArchiveExtensions(self)

Registry_swigregister = _osgDB.Registry_swigregister
Registry_swigregister(Registry)

def Registry_instance(erase = False):
  """
    instance(bool erase = False) -> Registry
    Registry_instance() -> Registry
    """
  return _osgDB.Registry_instance(erase)


def readCommandLine(*args):
  """readCommandLine(ArgumentParser parser)"""
  return _osgDB.readCommandLine(*args)
class PluginFunctionProxy(_object):
    """Proxy of C++ osgDB::PluginFunctionProxy class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PluginFunctionProxy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PluginFunctionProxy, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, CPluginFunction function) -> PluginFunctionProxy"""
        this = _osgDB.new_PluginFunctionProxy(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _osgDB.delete_PluginFunctionProxy
    __del__ = lambda self : None;
PluginFunctionProxy_swigregister = _osgDB.PluginFunctionProxy_swigregister
PluginFunctionProxy_swigregister(PluginFunctionProxy)



