# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_osgManipulator', [dirname(__file__)])
        except ImportError:
            import _osgManipulator
            return _osgManipulator
        if fp is not None:
            try:
                _mod = imp.load_module('_osgManipulator', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _osgManipulator = swig_import_helper()
    del swig_import_helper
else:
    import _osgManipulator
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    """Proxy of C++ swig::SwigPyIterator class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _osgManipulator.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self):
        """value(self) -> PyObject"""
        return _osgManipulator.SwigPyIterator_value(self)

    def incr(self, n = 1):
        """
        incr(self, size_t n = 1) -> SwigPyIterator
        incr(self) -> SwigPyIterator
        """
        return _osgManipulator.SwigPyIterator_incr(self, n)

    def decr(self, n = 1):
        """
        decr(self, size_t n = 1) -> SwigPyIterator
        decr(self) -> SwigPyIterator
        """
        return _osgManipulator.SwigPyIterator_decr(self, n)

    def distance(self, *args):
        """distance(self, SwigPyIterator x) -> ptrdiff_t"""
        return _osgManipulator.SwigPyIterator_distance(self, *args)

    def equal(self, *args):
        """equal(self, SwigPyIterator x) -> bool"""
        return _osgManipulator.SwigPyIterator_equal(self, *args)

    def copy(self):
        """copy(self) -> SwigPyIterator"""
        return _osgManipulator.SwigPyIterator_copy(self)

    def next(self):
        """next(self) -> PyObject"""
        return _osgManipulator.SwigPyIterator_next(self)

    def __next__(self):
        """__next__(self) -> PyObject"""
        return _osgManipulator.SwigPyIterator___next__(self)

    def previous(self):
        """previous(self) -> PyObject"""
        return _osgManipulator.SwigPyIterator_previous(self)

    def advance(self, *args):
        """advance(self, ptrdiff_t n) -> SwigPyIterator"""
        return _osgManipulator.SwigPyIterator_advance(self, *args)

    def __eq__(self, *args):
        """__eq__(self, SwigPyIterator x) -> bool"""
        return _osgManipulator.SwigPyIterator___eq__(self, *args)

    def __ne__(self, *args):
        """__ne__(self, SwigPyIterator x) -> bool"""
        return _osgManipulator.SwigPyIterator___ne__(self, *args)

    def __iadd__(self, *args):
        """__iadd__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _osgManipulator.SwigPyIterator___iadd__(self, *args)

    def __isub__(self, *args):
        """__isub__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _osgManipulator.SwigPyIterator___isub__(self, *args)

    def __add__(self, *args):
        """__add__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _osgManipulator.SwigPyIterator___add__(self, *args)

    def __sub__(self, *args):
        """
        __sub__(self, ptrdiff_t n) -> SwigPyIterator
        __sub__(self, SwigPyIterator x) -> ptrdiff_t
        """
        return _osgManipulator.SwigPyIterator___sub__(self, *args)

    def __iter__(self): return self
SwigPyIterator_swigregister = _osgManipulator.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import osg
OSGMANIPULATOR_EXPORT_ = _osgManipulator.OSGMANIPULATOR_EXPORT_
OSGMANIPULATOR_SELECTION = _osgManipulator.OSGMANIPULATOR_SELECTION
_OSG_ANTISQUISH_ = _osgManipulator._OSG_ANTISQUISH_
class AntiSquish(osg.MatrixTransform):
    """Proxy of C++ osgManipulator::AntiSquish class"""
    __swig_setmethods__ = {}
    for _s in [osg.MatrixTransform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AntiSquish, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.MatrixTransform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AntiSquish, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> AntiSquish
        __init__(self, Vec3d pivot) -> AntiSquish
        __init__(self, Vec3d pivot, Vec3d position) -> AntiSquish
        __init__(self, AntiSquish pat, CopyOp copyop = SHALLOW_COPY) -> AntiSquish
        __init__(self, AntiSquish pat) -> AntiSquish
        """
        this = _osgManipulator.new_AntiSquish(*args)
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.AntiSquish_cloneType(self)

    def clone(self, *args):
        """clone(self, CopyOp copyop) -> Object"""
        return _osgManipulator.AntiSquish_clone(self, *args)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.AntiSquish_isSameKindAs(self, *args)

    def setPivot(self, *args):
        """setPivot(self, Vec3d pvt)"""
        return _osgManipulator.AntiSquish_setPivot(self, *args)

    def getPivot(self):
        """getPivot(self) -> Vec3d"""
        return _osgManipulator.AntiSquish_getPivot(self)

    def setPosition(self, *args):
        """setPosition(self, Vec3d pos)"""
        return _osgManipulator.AntiSquish_setPosition(self, *args)

    def getPosition(self):
        """getPosition(self) -> Vec3d"""
        return _osgManipulator.AntiSquish_getPosition(self)

    __swig_destroy__ = _osgManipulator.delete_AntiSquish
    __del__ = lambda self : None;
    def computeUnSquishedMatrix(self, *args):
        """computeUnSquishedMatrix(self, Matrix arg0, bool flag) -> Matrix"""
        return _osgManipulator.AntiSquish_computeUnSquishedMatrix(self, *args)

AntiSquish_swigregister = _osgManipulator.AntiSquish_swigregister
AntiSquish_swigregister(AntiSquish)

OSGMANIPULATOR_COMMAND = _osgManipulator.OSGMANIPULATOR_COMMAND
class MotionCommand(osg.Referenced):
    """Proxy of C++ osgManipulator::MotionCommand class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MotionCommand, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, MotionCommand, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    NONE = _osgManipulator.MotionCommand_NONE
    START = _osgManipulator.MotionCommand_START
    MOVE = _osgManipulator.MotionCommand_MOVE
    FINISH = _osgManipulator.MotionCommand_FINISH
    def createCommandInverse(self):
        """createCommandInverse(self) -> MotionCommand"""
        return _osgManipulator.MotionCommand_createCommandInverse(self)

    def getMotionMatrix(self):
        """getMotionMatrix(self) -> Matrix"""
        return _osgManipulator.MotionCommand_getMotionMatrix(self)

    def setLocalToWorldAndWorldToLocal(self, *args):
        """setLocalToWorldAndWorldToLocal(self, Matrix localToWorld, Matrix worldToLocal)"""
        return _osgManipulator.MotionCommand_setLocalToWorldAndWorldToLocal(self, *args)

    def getLocalToWorld(self):
        """getLocalToWorld(self) -> Matrix"""
        return _osgManipulator.MotionCommand_getLocalToWorld(self)

    def getWorldToLocal(self):
        """getWorldToLocal(self) -> Matrix"""
        return _osgManipulator.MotionCommand_getWorldToLocal(self)

    def setStage(self, *args):
        """setStage(self, Stage s)"""
        return _osgManipulator.MotionCommand_setStage(self, *args)

    def getStage(self):
        """getStage(self) -> Stage"""
        return _osgManipulator.MotionCommand_getStage(self)

MotionCommand_swigregister = _osgManipulator.MotionCommand_swigregister
MotionCommand_swigregister(MotionCommand)

class TranslateInLineCommand(MotionCommand):
    """Proxy of C++ osgManipulator::TranslateInLineCommand class"""
    __swig_setmethods__ = {}
    for _s in [MotionCommand]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TranslateInLineCommand, name, value)
    __swig_getmethods__ = {}
    for _s in [MotionCommand]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TranslateInLineCommand, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> TranslateInLineCommand
        __init__(self, osg::LineSegment::vec_type s, osg::LineSegment::vec_type e) -> TranslateInLineCommand
        """
        this = _osgManipulator.new_TranslateInLineCommand(*args)
        try: self.this.append(this)
        except: self.this = this
    def createCommandInverse(self):
        """createCommandInverse(self) -> MotionCommand"""
        return _osgManipulator.TranslateInLineCommand_createCommandInverse(self)

    def setLine(self, *args):
        """setLine(self, osg::LineSegment::vec_type s, osg::LineSegment::vec_type e)"""
        return _osgManipulator.TranslateInLineCommand_setLine(self, *args)

    def getLineStart(self):
        """getLineStart(self) -> osg::LineSegment::vec_type"""
        return _osgManipulator.TranslateInLineCommand_getLineStart(self)

    def getLineEnd(self):
        """getLineEnd(self) -> osg::LineSegment::vec_type"""
        return _osgManipulator.TranslateInLineCommand_getLineEnd(self)

    def setTranslation(self, *args):
        """setTranslation(self, Vec3 t)"""
        return _osgManipulator.TranslateInLineCommand_setTranslation(self, *args)

    def getTranslation(self):
        """getTranslation(self) -> Vec3d"""
        return _osgManipulator.TranslateInLineCommand_getTranslation(self)

    def getMotionMatrix(self):
        """getMotionMatrix(self) -> Matrix"""
        return _osgManipulator.TranslateInLineCommand_getMotionMatrix(self)

TranslateInLineCommand_swigregister = _osgManipulator.TranslateInLineCommand_swigregister
TranslateInLineCommand_swigregister(TranslateInLineCommand)

class TranslateInPlaneCommand(MotionCommand):
    """Proxy of C++ osgManipulator::TranslateInPlaneCommand class"""
    __swig_setmethods__ = {}
    for _s in [MotionCommand]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TranslateInPlaneCommand, name, value)
    __swig_getmethods__ = {}
    for _s in [MotionCommand]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TranslateInPlaneCommand, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> TranslateInPlaneCommand
        __init__(self, Plane plane) -> TranslateInPlaneCommand
        """
        this = _osgManipulator.new_TranslateInPlaneCommand(*args)
        try: self.this.append(this)
        except: self.this = this
    def createCommandInverse(self):
        """createCommandInverse(self) -> MotionCommand"""
        return _osgManipulator.TranslateInPlaneCommand_createCommandInverse(self)

    def setPlane(self, *args):
        """setPlane(self, Plane plane)"""
        return _osgManipulator.TranslateInPlaneCommand_setPlane(self, *args)

    def getPlane(self):
        """getPlane(self) -> Plane"""
        return _osgManipulator.TranslateInPlaneCommand_getPlane(self)

    def setTranslation(self, *args):
        """setTranslation(self, Vec3d t)"""
        return _osgManipulator.TranslateInPlaneCommand_setTranslation(self, *args)

    def getTranslation(self):
        """getTranslation(self) -> Vec3d"""
        return _osgManipulator.TranslateInPlaneCommand_getTranslation(self)

    def setReferencePoint(self, *args):
        """setReferencePoint(self, Vec3d rp)"""
        return _osgManipulator.TranslateInPlaneCommand_setReferencePoint(self, *args)

    def getReferencePoint(self):
        """getReferencePoint(self) -> Vec3d"""
        return _osgManipulator.TranslateInPlaneCommand_getReferencePoint(self)

    def getMotionMatrix(self):
        """getMotionMatrix(self) -> Matrix"""
        return _osgManipulator.TranslateInPlaneCommand_getMotionMatrix(self)

TranslateInPlaneCommand_swigregister = _osgManipulator.TranslateInPlaneCommand_swigregister
TranslateInPlaneCommand_swigregister(TranslateInPlaneCommand)

class Scale1DCommand(MotionCommand):
    """Proxy of C++ osgManipulator::Scale1DCommand class"""
    __swig_setmethods__ = {}
    for _s in [MotionCommand]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Scale1DCommand, name, value)
    __swig_getmethods__ = {}
    for _s in [MotionCommand]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Scale1DCommand, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> Scale1DCommand"""
        this = _osgManipulator.new_Scale1DCommand()
        try: self.this.append(this)
        except: self.this = this
    def createCommandInverse(self):
        """createCommandInverse(self) -> MotionCommand"""
        return _osgManipulator.Scale1DCommand_createCommandInverse(self)

    def setScale(self, *args):
        """setScale(self, double s)"""
        return _osgManipulator.Scale1DCommand_setScale(self, *args)

    def getScale(self):
        """getScale(self) -> double"""
        return _osgManipulator.Scale1DCommand_getScale(self)

    def setScaleCenter(self, *args):
        """setScaleCenter(self, double center)"""
        return _osgManipulator.Scale1DCommand_setScaleCenter(self, *args)

    def getScaleCenter(self):
        """getScaleCenter(self) -> double"""
        return _osgManipulator.Scale1DCommand_getScaleCenter(self)

    def setReferencePoint(self, *args):
        """setReferencePoint(self, double rp)"""
        return _osgManipulator.Scale1DCommand_setReferencePoint(self, *args)

    def getReferencePoint(self):
        """getReferencePoint(self) -> double"""
        return _osgManipulator.Scale1DCommand_getReferencePoint(self)

    def setMinScale(self, *args):
        """setMinScale(self, double min)"""
        return _osgManipulator.Scale1DCommand_setMinScale(self, *args)

    def getMinScale(self):
        """getMinScale(self) -> double"""
        return _osgManipulator.Scale1DCommand_getMinScale(self)

    def getMotionMatrix(self):
        """getMotionMatrix(self) -> Matrix"""
        return _osgManipulator.Scale1DCommand_getMotionMatrix(self)

Scale1DCommand_swigregister = _osgManipulator.Scale1DCommand_swigregister
Scale1DCommand_swigregister(Scale1DCommand)

class Scale2DCommand(MotionCommand):
    """Proxy of C++ osgManipulator::Scale2DCommand class"""
    __swig_setmethods__ = {}
    for _s in [MotionCommand]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Scale2DCommand, name, value)
    __swig_getmethods__ = {}
    for _s in [MotionCommand]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Scale2DCommand, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> Scale2DCommand"""
        this = _osgManipulator.new_Scale2DCommand()
        try: self.this.append(this)
        except: self.this = this
    def createCommandInverse(self):
        """createCommandInverse(self) -> MotionCommand"""
        return _osgManipulator.Scale2DCommand_createCommandInverse(self)

    def setScale(self, *args):
        """setScale(self, Vec2d s)"""
        return _osgManipulator.Scale2DCommand_setScale(self, *args)

    def getScale(self):
        """getScale(self) -> Vec2d"""
        return _osgManipulator.Scale2DCommand_getScale(self)

    def setScaleCenter(self, *args):
        """setScaleCenter(self, Vec2d center)"""
        return _osgManipulator.Scale2DCommand_setScaleCenter(self, *args)

    def getScaleCenter(self):
        """getScaleCenter(self) -> Vec2d"""
        return _osgManipulator.Scale2DCommand_getScaleCenter(self)

    def setReferencePoint(self, *args):
        """setReferencePoint(self, Vec2d rp)"""
        return _osgManipulator.Scale2DCommand_setReferencePoint(self, *args)

    def getReferencePoint(self):
        """getReferencePoint(self) -> Vec2d"""
        return _osgManipulator.Scale2DCommand_getReferencePoint(self)

    def setMinScale(self, *args):
        """setMinScale(self, Vec2d min)"""
        return _osgManipulator.Scale2DCommand_setMinScale(self, *args)

    def getMinScale(self):
        """getMinScale(self) -> Vec2d"""
        return _osgManipulator.Scale2DCommand_getMinScale(self)

    def getMotionMatrix(self):
        """getMotionMatrix(self) -> Matrix"""
        return _osgManipulator.Scale2DCommand_getMotionMatrix(self)

Scale2DCommand_swigregister = _osgManipulator.Scale2DCommand_swigregister
Scale2DCommand_swigregister(Scale2DCommand)

class ScaleUniformCommand(MotionCommand):
    """Proxy of C++ osgManipulator::ScaleUniformCommand class"""
    __swig_setmethods__ = {}
    for _s in [MotionCommand]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ScaleUniformCommand, name, value)
    __swig_getmethods__ = {}
    for _s in [MotionCommand]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ScaleUniformCommand, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> ScaleUniformCommand"""
        this = _osgManipulator.new_ScaleUniformCommand()
        try: self.this.append(this)
        except: self.this = this
    def createCommandInverse(self):
        """createCommandInverse(self) -> MotionCommand"""
        return _osgManipulator.ScaleUniformCommand_createCommandInverse(self)

    def setScale(self, *args):
        """setScale(self, double s)"""
        return _osgManipulator.ScaleUniformCommand_setScale(self, *args)

    def getScale(self):
        """getScale(self) -> double"""
        return _osgManipulator.ScaleUniformCommand_getScale(self)

    def setScaleCenter(self, *args):
        """setScaleCenter(self, Vec3d center)"""
        return _osgManipulator.ScaleUniformCommand_setScaleCenter(self, *args)

    def getScaleCenter(self):
        """getScaleCenter(self) -> Vec3d"""
        return _osgManipulator.ScaleUniformCommand_getScaleCenter(self)

    def getMotionMatrix(self):
        """getMotionMatrix(self) -> Matrix"""
        return _osgManipulator.ScaleUniformCommand_getMotionMatrix(self)

ScaleUniformCommand_swigregister = _osgManipulator.ScaleUniformCommand_swigregister
ScaleUniformCommand_swigregister(ScaleUniformCommand)

class Rotate3DCommand(MotionCommand):
    """Proxy of C++ osgManipulator::Rotate3DCommand class"""
    __swig_setmethods__ = {}
    for _s in [MotionCommand]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Rotate3DCommand, name, value)
    __swig_getmethods__ = {}
    for _s in [MotionCommand]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Rotate3DCommand, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> Rotate3DCommand"""
        this = _osgManipulator.new_Rotate3DCommand()
        try: self.this.append(this)
        except: self.this = this
    def createCommandInverse(self):
        """createCommandInverse(self) -> MotionCommand"""
        return _osgManipulator.Rotate3DCommand_createCommandInverse(self)

    def setRotation(self, *args):
        """setRotation(self, Quat rotation)"""
        return _osgManipulator.Rotate3DCommand_setRotation(self, *args)

    def getRotation(self):
        """getRotation(self) -> Quat"""
        return _osgManipulator.Rotate3DCommand_getRotation(self)

    def getMotionMatrix(self):
        """getMotionMatrix(self) -> Matrix"""
        return _osgManipulator.Rotate3DCommand_getMotionMatrix(self)

Rotate3DCommand_swigregister = _osgManipulator.Rotate3DCommand_swigregister
Rotate3DCommand_swigregister(Rotate3DCommand)

OSGMANIPULATOR_DRAGGER = _osgManipulator.OSGMANIPULATOR_DRAGGER

def computeNodePathToRoot(*args):
  """computeNodePathToRoot(Node node, NodePath np)"""
  return _osgManipulator.computeNodePathToRoot(*args)
class DraggerCallback(osg.Object):
    """Proxy of C++ osgManipulator::DraggerCallback class"""
    __swig_setmethods__ = {}
    for _s in [osg.Object]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DraggerCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Object]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, DraggerCallback, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> DraggerCallback
        __init__(self, DraggerCallback arg0, CopyOp copyop = SHALLOW_COPY) -> DraggerCallback
        __init__(self, DraggerCallback arg0) -> DraggerCallback
        """
        this = _osgManipulator.new_DraggerCallback(*args)
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.DraggerCallback_cloneType(self)

    def clone(self, *args):
        """clone(self, CopyOp copyop) -> Object"""
        return _osgManipulator.DraggerCallback_clone(self, *args)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.DraggerCallback_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.DraggerCallback_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.DraggerCallback_className(self)

    def receive(self, *args):
        """
        receive(self, MotionCommand arg0) -> bool
        receive(self, TranslateInLineCommand command) -> bool
        receive(self, TranslateInPlaneCommand command) -> bool
        receive(self, Scale1DCommand command) -> bool
        receive(self, Scale2DCommand command) -> bool
        receive(self, ScaleUniformCommand command) -> bool
        receive(self, Rotate3DCommand command) -> bool
        """
        return _osgManipulator.DraggerCallback_receive(self, *args)

    __swig_destroy__ = _osgManipulator.delete_DraggerCallback
    __del__ = lambda self : None;
DraggerCallback_swigregister = _osgManipulator.DraggerCallback_swigregister
DraggerCallback_swigregister(DraggerCallback)

class DraggerTransformCallback(DraggerCallback):
    """Proxy of C++ osgManipulator::DraggerTransformCallback class"""
    __swig_setmethods__ = {}
    for _s in [DraggerCallback]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DraggerTransformCallback, name, value)
    __swig_getmethods__ = {}
    for _s in [DraggerCallback]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, DraggerTransformCallback, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, MatrixTransform transform) -> DraggerTransformCallback"""
        this = _osgManipulator.new_DraggerTransformCallback(*args)
        try: self.this.append(this)
        except: self.this = this
    def receive(self, *args):
        """receive(self, MotionCommand arg0) -> bool"""
        return _osgManipulator.DraggerTransformCallback_receive(self, *args)

    def getTransform(self, *args):
        """
        getTransform(self) -> MatrixTransform
        getTransform(self) -> MatrixTransform
        """
        return _osgManipulator.DraggerTransformCallback_getTransform(self, *args)

    __swig_destroy__ = _osgManipulator.delete_DraggerTransformCallback
    __del__ = lambda self : None;
DraggerTransformCallback_swigregister = _osgManipulator.DraggerTransformCallback_swigregister
DraggerTransformCallback_swigregister(DraggerTransformCallback)

class PointerInfo(_object):
    """Proxy of C++ osgManipulator::PointerInfo class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PointerInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PointerInfo, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> PointerInfo
        __init__(self, PointerInfo rhs) -> PointerInfo
        """
        this = _osgManipulator.new_PointerInfo(*args)
        try: self.this.append(this)
        except: self.this = this
    def reset(self):
        """reset(self)"""
        return _osgManipulator.PointerInfo_reset(self)

    def completed(self):
        """completed(self) -> bool"""
        return _osgManipulator.PointerInfo_completed(self)

    def next(self):
        """next(self)"""
        return _osgManipulator.PointerInfo_next(self)

    def getLocalIntersectPoint(self):
        """getLocalIntersectPoint(self) -> Vec3d"""
        return _osgManipulator.PointerInfo_getLocalIntersectPoint(self)

    def setNearFarPoints(self, *args):
        """setNearFarPoints(self, Vec3d nearPoint, Vec3d farPoint)"""
        return _osgManipulator.PointerInfo_setNearFarPoints(self, *args)

    def getEyeDir(self):
        """getEyeDir(self) -> Vec3d"""
        return _osgManipulator.PointerInfo_getEyeDir(self)

    def getNearFarPoints(self, *args):
        """getNearFarPoints(self, Vec3d nearPoint, Vec3d farPoint)"""
        return _osgManipulator.PointerInfo_getNearFarPoints(self, *args)

    def contains(self, *args):
        """contains(self, Node node) -> bool"""
        return _osgManipulator.PointerInfo_contains(self, *args)

    def setCamera(self, *args):
        """setCamera(self, Camera camera)"""
        return _osgManipulator.PointerInfo_setCamera(self, *args)

    def addIntersection(self, *args):
        """addIntersection(self, NodePath nodePath, Vec3d intersectionPoint)"""
        return _osgManipulator.PointerInfo_addIntersection(self, *args)

    def setMousePosition(self, *args):
        """setMousePosition(self, float pixel_x, float pixel_y)"""
        return _osgManipulator.PointerInfo_setMousePosition(self, *args)

    __swig_setmethods__["_hitList"] = _osgManipulator.PointerInfo__hitList_set
    __swig_getmethods__["_hitList"] = _osgManipulator.PointerInfo__hitList_get
    if _newclass:_hitList = _swig_property(_osgManipulator.PointerInfo__hitList_get, _osgManipulator.PointerInfo__hitList_set)
    __swig_setmethods__["_hitIter"] = _osgManipulator.PointerInfo__hitIter_set
    __swig_getmethods__["_hitIter"] = _osgManipulator.PointerInfo__hitIter_get
    if _newclass:_hitIter = _swig_property(_osgManipulator.PointerInfo__hitIter_get, _osgManipulator.PointerInfo__hitIter_set)
    __swig_destroy__ = _osgManipulator.delete_PointerInfo
    __del__ = lambda self : None;
PointerInfo_swigregister = _osgManipulator.PointerInfo_swigregister
PointerInfo_swigregister(PointerInfo)

class Dragger(osg.MatrixTransform):
    """Proxy of C++ osgManipulator::Dragger class"""
    __swig_setmethods__ = {}
    for _s in [osg.MatrixTransform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Dragger, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.MatrixTransform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Dragger, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.Dragger_cloneType(self)

    def clone(self, *args):
        """clone(self, CopyOp copyop) -> Object"""
        return _osgManipulator.Dragger_clone(self, *args)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.Dragger_isSameKindAs(self, *args)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.Dragger_className(self)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.Dragger_libraryName(self)

    def accept(self, *args):
        """accept(self, NodeVisitor nv)"""
        return _osgManipulator.Dragger_accept(self, *args)

    def setParentDragger(self, *args):
        """setParentDragger(self, Dragger parent)"""
        return _osgManipulator.Dragger_setParentDragger(self, *args)

    def getParentDragger(self, *args):
        """
        getParentDragger(self) -> Dragger
        getParentDragger(self) -> Dragger
        """
        return _osgManipulator.Dragger_getParentDragger(self, *args)

    def getComposite(self, *args):
        """
        getComposite(self) -> CompositeDragger
        getComposite(self) -> CompositeDragger
        """
        return _osgManipulator.Dragger_getComposite(self, *args)

    def setHandleEvents(self, *args):
        """setHandleEvents(self, bool flag)"""
        return _osgManipulator.Dragger_setHandleEvents(self, *args)

    def getHandleEvents(self):
        """getHandleEvents(self) -> bool"""
        return _osgManipulator.Dragger_getHandleEvents(self)

    def setActivationModKeyMask(self, *args):
        """setActivationModKeyMask(self, unsigned int mask)"""
        return _osgManipulator.Dragger_setActivationModKeyMask(self, *args)

    def getActivationModKeyMask(self):
        """getActivationModKeyMask(self) -> unsigned int"""
        return _osgManipulator.Dragger_getActivationModKeyMask(self)

    def setActivationKeyEvent(self, *args):
        """setActivationKeyEvent(self, int key)"""
        return _osgManipulator.Dragger_setActivationKeyEvent(self, *args)

    def getActivationKeyEvent(self):
        """getActivationKeyEvent(self) -> int"""
        return _osgManipulator.Dragger_getActivationKeyEvent(self)

    def traverse(self, *args):
        """traverse(self, NodeVisitor nv)"""
        return _osgManipulator.Dragger_traverse(self, *args)

    def handle(self, *args):
        """
        handle(self, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter aa) -> bool
        handle(self, PointerInfo arg0, osgGA::GUIEventAdapter arg1, osgGA::GUIActionAdapter arg2) -> bool
        """
        return _osgManipulator.Dragger_handle(self, *args)

    def addConstraint(self, *args):
        """addConstraint(self, Constraint constraint)"""
        return _osgManipulator.Dragger_addConstraint(self, *args)

    def removeConstraint(self, *args):
        """removeConstraint(self, Constraint constraint)"""
        return _osgManipulator.Dragger_removeConstraint(self, *args)

    def getConstraints(self, *args):
        """
        getConstraints(self) -> Constraints
        getConstraints(self) -> Constraints
        """
        return _osgManipulator.Dragger_getConstraints(self, *args)

    def addDraggerCallback(self, *args):
        """addDraggerCallback(self, DraggerCallback dc)"""
        return _osgManipulator.Dragger_addDraggerCallback(self, *args)

    def removeDraggerCallback(self, *args):
        """removeDraggerCallback(self, DraggerCallback dc)"""
        return _osgManipulator.Dragger_removeDraggerCallback(self, *args)

    def getDraggerCallbacks(self, *args):
        """
        getDraggerCallbacks(self) -> DraggerCallbacks
        getDraggerCallbacks(self) -> DraggerCallbacks
        """
        return _osgManipulator.Dragger_getDraggerCallbacks(self, *args)

    def addTransformUpdating(self, *args):
        """addTransformUpdating(self, MatrixTransform transform)"""
        return _osgManipulator.Dragger_addTransformUpdating(self, *args)

    def removeTransformUpdating(self, *args):
        """removeTransformUpdating(self, MatrixTransform transform)"""
        return _osgManipulator.Dragger_removeTransformUpdating(self, *args)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.Dragger_setupDefaultGeometry(self)

    def receive(self, *args):
        """receive(self, MotionCommand command) -> bool"""
        return _osgManipulator.Dragger_receive(self, *args)

    def dispatch(self, *args):
        """dispatch(self, MotionCommand command)"""
        return _osgManipulator.Dragger_dispatch(self, *args)

    def setDraggerActive(self, *args):
        """setDraggerActive(self, bool active)"""
        return _osgManipulator.Dragger_setDraggerActive(self, *args)

    def getDraggerActive(self):
        """getDraggerActive(self) -> bool"""
        return _osgManipulator.Dragger_getDraggerActive(self)

Dragger_swigregister = _osgManipulator.Dragger_swigregister
Dragger_swigregister(Dragger)

class CompositeDragger(Dragger):
    """Proxy of C++ osgManipulator::CompositeDragger class"""
    __swig_setmethods__ = {}
    for _s in [Dragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CompositeDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [Dragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CompositeDragger, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.CompositeDragger_cloneType(self)

    def clone(self, *args):
        """clone(self, CopyOp copyop) -> Object"""
        return _osgManipulator.CompositeDragger_clone(self, *args)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.CompositeDragger_isSameKindAs(self, *args)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.CompositeDragger_className(self)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.CompositeDragger_libraryName(self)

    def accept(self, *args):
        """accept(self, NodeVisitor nv)"""
        return _osgManipulator.CompositeDragger_accept(self, *args)

    def getComposite(self, *args):
        """
        getComposite(self) -> CompositeDragger
        getComposite(self) -> CompositeDragger
        """
        return _osgManipulator.CompositeDragger_getComposite(self, *args)

    def setParentDragger(self, *args):
        """setParentDragger(self, Dragger parent)"""
        return _osgManipulator.CompositeDragger_setParentDragger(self, *args)

    def handle(self, *args):
        """handle(self, PointerInfo pi, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter aa) -> bool"""
        return _osgManipulator.CompositeDragger_handle(self, *args)

    def addDragger(self, *args):
        """addDragger(self, Dragger dragger) -> bool"""
        return _osgManipulator.CompositeDragger_addDragger(self, *args)

    def removeDragger(self, *args):
        """removeDragger(self, Dragger dragger) -> bool"""
        return _osgManipulator.CompositeDragger_removeDragger(self, *args)

    def getNumDraggers(self):
        """getNumDraggers(self) -> unsigned int"""
        return _osgManipulator.CompositeDragger_getNumDraggers(self)

    def getDragger(self, *args):
        """
        getDragger(self, unsigned int i) -> Dragger
        getDragger(self, unsigned int i) -> Dragger
        """
        return _osgManipulator.CompositeDragger_getDragger(self, *args)

    def containsDragger(self, *args):
        """containsDragger(self, Dragger dragger) -> bool"""
        return _osgManipulator.CompositeDragger_containsDragger(self, *args)

    def findDragger(self, *args):
        """findDragger(self, Dragger dragger) -> osgManipulator::CompositeDragger::DraggerList::iterator"""
        return _osgManipulator.CompositeDragger_findDragger(self, *args)

CompositeDragger_swigregister = _osgManipulator.CompositeDragger_swigregister
CompositeDragger_swigregister(CompositeDragger)


def setDrawableToAlwaysCull(*args):
  """setDrawableToAlwaysCull(Drawable drawable)"""
  return _osgManipulator.setDrawableToAlwaysCull(*args)

def setMaterialColor(*args):
  """setMaterialColor(Vec4 color, Node node)"""
  return _osgManipulator.setMaterialColor(*args)
OSGMANIPULATOR_COMMANDMANAGER = _osgManipulator.OSGMANIPULATOR_COMMANDMANAGER
class CommandManager(osg.Referenced):
    """Proxy of C++ osgManipulator::CommandManager class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CommandManager, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CommandManager, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> CommandManager"""
        this = _osgManipulator.new_CommandManager()
        try: self.this.append(this)
        except: self.this = this
    def connect(self, *args):
        """
        connect(self, Dragger dragger, Selection selection) -> bool
        connect(self, Dragger dragger, Constraint constraint) -> bool
        """
        return _osgManipulator.CommandManager_connect(self, *args)

    def disconnect(self, *args):
        """disconnect(self, Dragger dragger) -> bool"""
        return _osgManipulator.CommandManager_disconnect(self, *args)

    def getConnectedSelections(self, *args):
        """getConnectedSelections(self, Dragger dragger) -> Selections"""
        return _osgManipulator.CommandManager_getConnectedSelections(self, *args)

CommandManager_swigregister = _osgManipulator.CommandManager_swigregister
CommandManager_swigregister(CommandManager)

OSGMANIPULATOR_CONSTRAINT = _osgManipulator.OSGMANIPULATOR_CONSTRAINT
class Constraint(osg.Referenced):
    """Proxy of C++ osgManipulator::Constraint class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Constraint, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Constraint, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def constrain(self, *args):
        """
        constrain(self, MotionCommand arg0) -> bool
        constrain(self, TranslateInLineCommand command) -> bool
        constrain(self, TranslateInPlaneCommand command) -> bool
        constrain(self, Scale1DCommand command) -> bool
        constrain(self, Scale2DCommand command) -> bool
        constrain(self, ScaleUniformCommand command) -> bool
        """
        return _osgManipulator.Constraint_constrain(self, *args)

Constraint_swigregister = _osgManipulator.Constraint_swigregister
Constraint_swigregister(Constraint)

class GridConstraint(Constraint):
    """Proxy of C++ osgManipulator::GridConstraint class"""
    __swig_setmethods__ = {}
    for _s in [Constraint]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GridConstraint, name, value)
    __swig_getmethods__ = {}
    for _s in [Constraint]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GridConstraint, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """__init__(self, Node refNode, Vec3d origin, Vec3d spacing) -> GridConstraint"""
        this = _osgManipulator.new_GridConstraint(*args)
        try: self.this.append(this)
        except: self.this = this
    def setOrigin(self, *args):
        """setOrigin(self, Vec3d origin)"""
        return _osgManipulator.GridConstraint_setOrigin(self, *args)

    def getOrigin(self):
        """getOrigin(self) -> Vec3d"""
        return _osgManipulator.GridConstraint_getOrigin(self)

    def setSpacing(self, *args):
        """setSpacing(self, Vec3d spacing)"""
        return _osgManipulator.GridConstraint_setSpacing(self, *args)

    def getSpacing(self):
        """getSpacing(self) -> Vec3d"""
        return _osgManipulator.GridConstraint_getSpacing(self)

    def constrain(self, *args):
        """
        constrain(self, TranslateInLineCommand command) -> bool
        constrain(self, TranslateInPlaneCommand command) -> bool
        constrain(self, Scale1DCommand command) -> bool
        constrain(self, Scale2DCommand command) -> bool
        constrain(self, ScaleUniformCommand command) -> bool
        """
        return _osgManipulator.GridConstraint_constrain(self, *args)

GridConstraint_swigregister = _osgManipulator.GridConstraint_swigregister
GridConstraint_swigregister(GridConstraint)

OSGMANIPULATOR_PROJECTOR = _osgManipulator.OSGMANIPULATOR_PROJECTOR
class Projector(osg.Referenced):
    """Proxy of C++ osgManipulator::Projector class"""
    __swig_setmethods__ = {}
    for _s in [osg.Referenced]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Projector, name, value)
    __swig_getmethods__ = {}
    for _s in [osg.Referenced]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Projector, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def project(self, *args):
        """project(self, PointerInfo pi, Vec3d projectedPoint) -> bool"""
        return _osgManipulator.Projector_project(self, *args)

    def setLocalToWorld(self, *args):
        """setLocalToWorld(self, Matrix localToWorld)"""
        return _osgManipulator.Projector_setLocalToWorld(self, *args)

    def getLocalToWorld(self):
        """getLocalToWorld(self) -> Matrix"""
        return _osgManipulator.Projector_getLocalToWorld(self)

    def getWorldToLocal(self):
        """getWorldToLocal(self) -> Matrix"""
        return _osgManipulator.Projector_getWorldToLocal(self)

Projector_swigregister = _osgManipulator.Projector_swigregister
Projector_swigregister(Projector)

class LineProjector(Projector):
    """Proxy of C++ osgManipulator::LineProjector class"""
    __swig_setmethods__ = {}
    for _s in [Projector]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, LineProjector, name, value)
    __swig_getmethods__ = {}
    for _s in [Projector]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, LineProjector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> LineProjector
        __init__(self, osg::LineSegment::vec_type s, osg::LineSegment::vec_type e) -> LineProjector
        """
        this = _osgManipulator.new_LineProjector(*args)
        try: self.this.append(this)
        except: self.this = this
    def setLine(self, *args):
        """setLine(self, osg::LineSegment::vec_type s, osg::LineSegment::vec_type e)"""
        return _osgManipulator.LineProjector_setLine(self, *args)

    def getLineStart(self, *args):
        """
        getLineStart(self) -> osg::LineSegment::vec_type
        getLineStart(self) -> osg::LineSegment::vec_type
        """
        return _osgManipulator.LineProjector_getLineStart(self, *args)

    def getLineEnd(self, *args):
        """
        getLineEnd(self) -> osg::LineSegment::vec_type
        getLineEnd(self) -> osg::LineSegment::vec_type
        """
        return _osgManipulator.LineProjector_getLineEnd(self, *args)

    def project(self, *args):
        """project(self, PointerInfo pi, Vec3d projectedPoint) -> bool"""
        return _osgManipulator.LineProjector_project(self, *args)

LineProjector_swigregister = _osgManipulator.LineProjector_swigregister
LineProjector_swigregister(LineProjector)

class PlaneProjector(Projector):
    """Proxy of C++ osgManipulator::PlaneProjector class"""
    __swig_setmethods__ = {}
    for _s in [Projector]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PlaneProjector, name, value)
    __swig_getmethods__ = {}
    for _s in [Projector]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PlaneProjector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> PlaneProjector
        __init__(self, Plane plane) -> PlaneProjector
        """
        this = _osgManipulator.new_PlaneProjector(*args)
        try: self.this.append(this)
        except: self.this = this
    def setPlane(self, *args):
        """setPlane(self, Plane plane)"""
        return _osgManipulator.PlaneProjector_setPlane(self, *args)

    def getPlane(self):
        """getPlane(self) -> Plane"""
        return _osgManipulator.PlaneProjector_getPlane(self)

    def project(self, *args):
        """project(self, PointerInfo pi, Vec3d projectedPoint) -> bool"""
        return _osgManipulator.PlaneProjector_project(self, *args)

PlaneProjector_swigregister = _osgManipulator.PlaneProjector_swigregister
PlaneProjector_swigregister(PlaneProjector)

class SphereProjector(Projector):
    """Proxy of C++ osgManipulator::SphereProjector class"""
    __swig_setmethods__ = {}
    for _s in [Projector]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SphereProjector, name, value)
    __swig_getmethods__ = {}
    for _s in [Projector]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SphereProjector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> SphereProjector
        __init__(self, Sphere sphere) -> SphereProjector
        """
        this = _osgManipulator.new_SphereProjector(*args)
        try: self.this.append(this)
        except: self.this = this
    def setSphere(self, *args):
        """setSphere(self, Sphere sphere)"""
        return _osgManipulator.SphereProjector_setSphere(self, *args)

    def getSphere(self):
        """getSphere(self) -> Sphere"""
        return _osgManipulator.SphereProjector_getSphere(self)

    def project(self, *args):
        """project(self, PointerInfo pi, Vec3d projectedPoint) -> bool"""
        return _osgManipulator.SphereProjector_project(self, *args)

    def isPointInFront(self, *args):
        """isPointInFront(self, PointerInfo pi, Matrix localToWorld) -> bool"""
        return _osgManipulator.SphereProjector_isPointInFront(self, *args)

    def setFront(self, *args):
        """setFront(self, bool front)"""
        return _osgManipulator.SphereProjector_setFront(self, *args)

SphereProjector_swigregister = _osgManipulator.SphereProjector_swigregister
SphereProjector_swigregister(SphereProjector)

class SpherePlaneProjector(SphereProjector):
    """Proxy of C++ osgManipulator::SpherePlaneProjector class"""
    __swig_setmethods__ = {}
    for _s in [SphereProjector]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpherePlaneProjector, name, value)
    __swig_getmethods__ = {}
    for _s in [SphereProjector]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SpherePlaneProjector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> SpherePlaneProjector
        __init__(self, Sphere sphere) -> SpherePlaneProjector
        """
        this = _osgManipulator.new_SpherePlaneProjector(*args)
        try: self.this.append(this)
        except: self.this = this
    def project(self, *args):
        """project(self, PointerInfo pi, Vec3d projectedPoint) -> bool"""
        return _osgManipulator.SpherePlaneProjector_project(self, *args)

    def isProjectionOnSphere(self):
        """isProjectionOnSphere(self) -> bool"""
        return _osgManipulator.SpherePlaneProjector_isProjectionOnSphere(self)

    def getRotation(self, *args):
        """
        getRotation(self, Vec3d p1, bool p1OnSphere, Vec3d p2, bool p2OnSphere, 
            float radialFactor = 0.0) -> Quat
        getRotation(self, Vec3d p1, bool p1OnSphere, Vec3d p2, bool p2OnSphere) -> Quat
        """
        return _osgManipulator.SpherePlaneProjector_getRotation(self, *args)

SpherePlaneProjector_swigregister = _osgManipulator.SpherePlaneProjector_swigregister
SpherePlaneProjector_swigregister(SpherePlaneProjector)

class CylinderProjector(Projector):
    """Proxy of C++ osgManipulator::CylinderProjector class"""
    __swig_setmethods__ = {}
    for _s in [Projector]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CylinderProjector, name, value)
    __swig_getmethods__ = {}
    for _s in [Projector]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CylinderProjector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> CylinderProjector
        __init__(self, Cylinder cylinder) -> CylinderProjector
        """
        this = _osgManipulator.new_CylinderProjector(*args)
        try: self.this.append(this)
        except: self.this = this
    def setCylinder(self, *args):
        """setCylinder(self, Cylinder cylinder)"""
        return _osgManipulator.CylinderProjector_setCylinder(self, *args)

    def getCylinder(self):
        """getCylinder(self) -> Cylinder"""
        return _osgManipulator.CylinderProjector_getCylinder(self)

    def project(self, *args):
        """project(self, PointerInfo pi, Vec3d projectedPoint) -> bool"""
        return _osgManipulator.CylinderProjector_project(self, *args)

    def isPointInFront(self, *args):
        """isPointInFront(self, PointerInfo pi, Matrix localToWorld) -> bool"""
        return _osgManipulator.CylinderProjector_isPointInFront(self, *args)

    def setFront(self, *args):
        """setFront(self, bool front)"""
        return _osgManipulator.CylinderProjector_setFront(self, *args)

CylinderProjector_swigregister = _osgManipulator.CylinderProjector_swigregister
CylinderProjector_swigregister(CylinderProjector)

class CylinderPlaneProjector(CylinderProjector):
    """Proxy of C++ osgManipulator::CylinderPlaneProjector class"""
    __swig_setmethods__ = {}
    for _s in [CylinderProjector]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CylinderPlaneProjector, name, value)
    __swig_getmethods__ = {}
    for _s in [CylinderProjector]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CylinderPlaneProjector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> CylinderPlaneProjector
        __init__(self, Cylinder cylinder) -> CylinderPlaneProjector
        """
        this = _osgManipulator.new_CylinderPlaneProjector(*args)
        try: self.this.append(this)
        except: self.this = this
    def project(self, *args):
        """project(self, PointerInfo pi, Vec3d projectedPoint) -> bool"""
        return _osgManipulator.CylinderPlaneProjector_project(self, *args)

    def isProjectionOnCylinder(self):
        """isProjectionOnCylinder(self) -> bool"""
        return _osgManipulator.CylinderPlaneProjector_isProjectionOnCylinder(self)

    def getRotation(self, *args):
        """getRotation(self, Vec3d p1, bool p1OnCyl, Vec3d p2, bool p2OnCyl) -> Quat"""
        return _osgManipulator.CylinderPlaneProjector_getRotation(self, *args)

CylinderPlaneProjector_swigregister = _osgManipulator.CylinderPlaneProjector_swigregister
CylinderPlaneProjector_swigregister(CylinderPlaneProjector)

OSGMANIPULATOR_ROTATECYLINDERDRAGGER = _osgManipulator.OSGMANIPULATOR_ROTATECYLINDERDRAGGER
class RotateCylinderDragger(Dragger):
    """Proxy of C++ osgManipulator::RotateCylinderDragger class"""
    __swig_setmethods__ = {}
    for _s in [Dragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, RotateCylinderDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [Dragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, RotateCylinderDragger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> RotateCylinderDragger"""
        this = _osgManipulator.new_RotateCylinderDragger()
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.RotateCylinderDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.RotateCylinderDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.RotateCylinderDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.RotateCylinderDragger_className(self)

    def handle(self, *args):
        """handle(self, PointerInfo pi, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter us) -> bool"""
        return _osgManipulator.RotateCylinderDragger_handle(self, *args)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.RotateCylinderDragger_setupDefaultGeometry(self)

    def setColor(self, *args):
        """setColor(self, Vec4 color)"""
        return _osgManipulator.RotateCylinderDragger_setColor(self, *args)

    def getColor(self):
        """getColor(self) -> Vec4"""
        return _osgManipulator.RotateCylinderDragger_getColor(self)

    def setPickColor(self, *args):
        """setPickColor(self, Vec4 color)"""
        return _osgManipulator.RotateCylinderDragger_setPickColor(self, *args)

    def getPickColor(self):
        """getPickColor(self) -> Vec4"""
        return _osgManipulator.RotateCylinderDragger_getPickColor(self)

RotateCylinderDragger_swigregister = _osgManipulator.RotateCylinderDragger_swigregister
RotateCylinderDragger_swigregister(RotateCylinderDragger)

OSGMANIPULATOR_ROTATESPHEREDRAGGER = _osgManipulator.OSGMANIPULATOR_ROTATESPHEREDRAGGER
class RotateSphereDragger(Dragger):
    """Proxy of C++ osgManipulator::RotateSphereDragger class"""
    __swig_setmethods__ = {}
    for _s in [Dragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, RotateSphereDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [Dragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, RotateSphereDragger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> RotateSphereDragger"""
        this = _osgManipulator.new_RotateSphereDragger()
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.RotateSphereDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.RotateSphereDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.RotateSphereDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.RotateSphereDragger_className(self)

    def handle(self, *args):
        """handle(self, PointerInfo arg0, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter us) -> bool"""
        return _osgManipulator.RotateSphereDragger_handle(self, *args)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.RotateSphereDragger_setupDefaultGeometry(self)

    def setColor(self, *args):
        """setColor(self, Vec4 color)"""
        return _osgManipulator.RotateSphereDragger_setColor(self, *args)

    def getColor(self):
        """getColor(self) -> Vec4"""
        return _osgManipulator.RotateSphereDragger_getColor(self)

    def setPickColor(self, *args):
        """setPickColor(self, Vec4 color)"""
        return _osgManipulator.RotateSphereDragger_setPickColor(self, *args)

    def getPickColor(self):
        """getPickColor(self) -> Vec4"""
        return _osgManipulator.RotateSphereDragger_getPickColor(self)

RotateSphereDragger_swigregister = _osgManipulator.RotateSphereDragger_swigregister
RotateSphereDragger_swigregister(RotateSphereDragger)

OSGMANIPULATOR_SCALE1DDRAGGER = _osgManipulator.OSGMANIPULATOR_SCALE1DDRAGGER
class Scale1DDragger(Dragger):
    """Proxy of C++ osgManipulator::Scale1DDragger class"""
    __swig_setmethods__ = {}
    for _s in [Dragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Scale1DDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [Dragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Scale1DDragger, name)
    __repr__ = _swig_repr
    SCALE_WITH_ORIGIN_AS_PIVOT = _osgManipulator.Scale1DDragger_SCALE_WITH_ORIGIN_AS_PIVOT
    SCALE_WITH_OPPOSITE_HANDLE_AS_PIVOT = _osgManipulator.Scale1DDragger_SCALE_WITH_OPPOSITE_HANDLE_AS_PIVOT
    def __init__(self, *args): 
        """
        __init__(self, ScaleMode scaleMode = SCALE_WITH_ORIGIN_AS_PIVOT) -> Scale1DDragger
        __init__(self) -> Scale1DDragger
        """
        this = _osgManipulator.new_Scale1DDragger(*args)
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.Scale1DDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.Scale1DDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.Scale1DDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.Scale1DDragger_className(self)

    def handle(self, *args):
        """handle(self, PointerInfo pi, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter us) -> bool"""
        return _osgManipulator.Scale1DDragger_handle(self, *args)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.Scale1DDragger_setupDefaultGeometry(self)

    def setMinScale(self, *args):
        """setMinScale(self, double min)"""
        return _osgManipulator.Scale1DDragger_setMinScale(self, *args)

    def getMinScale(self):
        """getMinScale(self) -> double"""
        return _osgManipulator.Scale1DDragger_getMinScale(self)

    def setColor(self, *args):
        """setColor(self, Vec4 color)"""
        return _osgManipulator.Scale1DDragger_setColor(self, *args)

    def getColor(self):
        """getColor(self) -> Vec4"""
        return _osgManipulator.Scale1DDragger_getColor(self)

    def setPickColor(self, *args):
        """setPickColor(self, Vec4 color)"""
        return _osgManipulator.Scale1DDragger_setPickColor(self, *args)

    def getPickColor(self):
        """getPickColor(self) -> Vec4"""
        return _osgManipulator.Scale1DDragger_getPickColor(self)

    def setLeftHandleNode(self, *args):
        """setLeftHandleNode(self, Node node)"""
        return _osgManipulator.Scale1DDragger_setLeftHandleNode(self, *args)

    def setRightHandleNode(self, *args):
        """setRightHandleNode(self, Node node)"""
        return _osgManipulator.Scale1DDragger_setRightHandleNode(self, *args)

    def getLeftHandleNode(self, *args):
        """
        getLeftHandleNode(self) -> Node
        getLeftHandleNode(self) -> Node
        """
        return _osgManipulator.Scale1DDragger_getLeftHandleNode(self, *args)

    def getRightHandleNode(self, *args):
        """
        getRightHandleNode(self) -> Node
        getRightHandleNode(self) -> Node
        """
        return _osgManipulator.Scale1DDragger_getRightHandleNode(self, *args)

    def setLeftHandlePosition(self, *args):
        """setLeftHandlePosition(self, double pos)"""
        return _osgManipulator.Scale1DDragger_setLeftHandlePosition(self, *args)

    def getLeftHandlePosition(self):
        """getLeftHandlePosition(self) -> double"""
        return _osgManipulator.Scale1DDragger_getLeftHandlePosition(self)

    def setRightHandlePosition(self, *args):
        """setRightHandlePosition(self, double pos)"""
        return _osgManipulator.Scale1DDragger_setRightHandlePosition(self, *args)

    def getRightHandlePosition(self):
        """getRightHandlePosition(self) -> double"""
        return _osgManipulator.Scale1DDragger_getRightHandlePosition(self)

Scale1DDragger_swigregister = _osgManipulator.Scale1DDragger_swigregister
Scale1DDragger_swigregister(Scale1DDragger)

OSGMANIPULATOR_SCALE2DDRAGGER = _osgManipulator.OSGMANIPULATOR_SCALE2DDRAGGER
class Scale2DDragger(Dragger):
    """Proxy of C++ osgManipulator::Scale2DDragger class"""
    __swig_setmethods__ = {}
    for _s in [Dragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Scale2DDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [Dragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Scale2DDragger, name)
    __repr__ = _swig_repr
    SCALE_WITH_ORIGIN_AS_PIVOT = _osgManipulator.Scale2DDragger_SCALE_WITH_ORIGIN_AS_PIVOT
    SCALE_WITH_OPPOSITE_HANDLE_AS_PIVOT = _osgManipulator.Scale2DDragger_SCALE_WITH_OPPOSITE_HANDLE_AS_PIVOT
    def __init__(self, *args): 
        """
        __init__(self, ScaleMode scaleMode = SCALE_WITH_ORIGIN_AS_PIVOT) -> Scale2DDragger
        __init__(self) -> Scale2DDragger
        """
        this = _osgManipulator.new_Scale2DDragger(*args)
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.Scale2DDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.Scale2DDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.Scale2DDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.Scale2DDragger_className(self)

    def handle(self, *args):
        """handle(self, PointerInfo pi, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter us) -> bool"""
        return _osgManipulator.Scale2DDragger_handle(self, *args)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.Scale2DDragger_setupDefaultGeometry(self)

    def setMinScale(self, *args):
        """setMinScale(self, Vec2d min)"""
        return _osgManipulator.Scale2DDragger_setMinScale(self, *args)

    def getMinScale(self):
        """getMinScale(self) -> Vec2d"""
        return _osgManipulator.Scale2DDragger_getMinScale(self)

    def setColor(self, *args):
        """setColor(self, Vec4 color)"""
        return _osgManipulator.Scale2DDragger_setColor(self, *args)

    def getColor(self):
        """getColor(self) -> Vec4"""
        return _osgManipulator.Scale2DDragger_getColor(self)

    def setPickColor(self, *args):
        """setPickColor(self, Vec4 color)"""
        return _osgManipulator.Scale2DDragger_setPickColor(self, *args)

    def getPickColor(self):
        """getPickColor(self) -> Vec4"""
        return _osgManipulator.Scale2DDragger_getPickColor(self)

    def setTopLeftHandleNode(self, *args):
        """setTopLeftHandleNode(self, Node node)"""
        return _osgManipulator.Scale2DDragger_setTopLeftHandleNode(self, *args)

    def getTopLeftHandleNode(self, *args):
        """
        getTopLeftHandleNode(self) -> Node
        getTopLeftHandleNode(self) -> Node
        """
        return _osgManipulator.Scale2DDragger_getTopLeftHandleNode(self, *args)

    def setBottomLeftHandleNode(self, *args):
        """setBottomLeftHandleNode(self, Node node)"""
        return _osgManipulator.Scale2DDragger_setBottomLeftHandleNode(self, *args)

    def getBottomLeftHandleNode(self, *args):
        """
        getBottomLeftHandleNode(self) -> Node
        getBottomLeftHandleNode(self) -> Node
        """
        return _osgManipulator.Scale2DDragger_getBottomLeftHandleNode(self, *args)

    def setTopRightHandleNode(self, *args):
        """setTopRightHandleNode(self, Node node)"""
        return _osgManipulator.Scale2DDragger_setTopRightHandleNode(self, *args)

    def getTopRightHandleNode(self, *args):
        """
        getTopRightHandleNode(self) -> Node
        getTopRightHandleNode(self) -> Node
        """
        return _osgManipulator.Scale2DDragger_getTopRightHandleNode(self, *args)

    def setBottomRightHandleNode(self, *args):
        """setBottomRightHandleNode(self, Node node)"""
        return _osgManipulator.Scale2DDragger_setBottomRightHandleNode(self, *args)

    def getBottomRightHandleNode(self, *args):
        """
        getBottomRightHandleNode(self) -> Node
        getBottomRightHandleNode(self) -> Node
        """
        return _osgManipulator.Scale2DDragger_getBottomRightHandleNode(self, *args)

    def setTopLeftHandlePosition(self, *args):
        """setTopLeftHandlePosition(self, Vec2d pos)"""
        return _osgManipulator.Scale2DDragger_setTopLeftHandlePosition(self, *args)

    def getTopLeftHandlePosition(self):
        """getTopLeftHandlePosition(self) -> Vec2d"""
        return _osgManipulator.Scale2DDragger_getTopLeftHandlePosition(self)

    def setBottomLeftHandlePosition(self, *args):
        """setBottomLeftHandlePosition(self, Vec2d pos)"""
        return _osgManipulator.Scale2DDragger_setBottomLeftHandlePosition(self, *args)

    def getBottomLeftHandlePosition(self):
        """getBottomLeftHandlePosition(self) -> Vec2d"""
        return _osgManipulator.Scale2DDragger_getBottomLeftHandlePosition(self)

    def setTopRightHandlePosition(self, *args):
        """setTopRightHandlePosition(self, Vec2d pos)"""
        return _osgManipulator.Scale2DDragger_setTopRightHandlePosition(self, *args)

    def getTopRightHandlePosition(self):
        """getTopRightHandlePosition(self) -> Vec2d"""
        return _osgManipulator.Scale2DDragger_getTopRightHandlePosition(self)

    def setBottomRightHandlePosition(self, *args):
        """setBottomRightHandlePosition(self, Vec2d pos)"""
        return _osgManipulator.Scale2DDragger_setBottomRightHandlePosition(self, *args)

    def getBottomRightHandlePosition(self):
        """getBottomRightHandlePosition(self) -> Vec2d"""
        return _osgManipulator.Scale2DDragger_getBottomRightHandlePosition(self)

Scale2DDragger_swigregister = _osgManipulator.Scale2DDragger_swigregister
Scale2DDragger_swigregister(Scale2DDragger)

OSGMANIPULATOR_SCALEAXISDRAGGER = _osgManipulator.OSGMANIPULATOR_SCALEAXISDRAGGER
class ScaleAxisDragger(CompositeDragger):
    """Proxy of C++ osgManipulator::ScaleAxisDragger class"""
    __swig_setmethods__ = {}
    for _s in [CompositeDragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ScaleAxisDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [CompositeDragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ScaleAxisDragger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> ScaleAxisDragger"""
        this = _osgManipulator.new_ScaleAxisDragger()
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.ScaleAxisDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.ScaleAxisDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.ScaleAxisDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.ScaleAxisDragger_className(self)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.ScaleAxisDragger_setupDefaultGeometry(self)

ScaleAxisDragger_swigregister = _osgManipulator.ScaleAxisDragger_swigregister
ScaleAxisDragger_swigregister(ScaleAxisDragger)

OSGMANIPULATOR_TABBOXDRAGGER = _osgManipulator.OSGMANIPULATOR_TABBOXDRAGGER
class TabBoxDragger(CompositeDragger):
    """Proxy of C++ osgManipulator::TabBoxDragger class"""
    __swig_setmethods__ = {}
    for _s in [CompositeDragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TabBoxDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [CompositeDragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TabBoxDragger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> TabBoxDragger"""
        this = _osgManipulator.new_TabBoxDragger()
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.TabBoxDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.TabBoxDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.TabBoxDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.TabBoxDragger_className(self)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.TabBoxDragger_setupDefaultGeometry(self)

    def setPlaneColor(self, *args):
        """setPlaneColor(self, Vec4 color)"""
        return _osgManipulator.TabBoxDragger_setPlaneColor(self, *args)

TabBoxDragger_swigregister = _osgManipulator.TabBoxDragger_swigregister
TabBoxDragger_swigregister(TabBoxDragger)

OSGMANIPULATOR_TABPLANEDRAGGER = _osgManipulator.OSGMANIPULATOR_TABPLANEDRAGGER
class TabPlaneDragger(CompositeDragger):
    """Proxy of C++ osgManipulator::TabPlaneDragger class"""
    __swig_setmethods__ = {}
    for _s in [CompositeDragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TabPlaneDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [CompositeDragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TabPlaneDragger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> TabPlaneDragger"""
        this = _osgManipulator.new_TabPlaneDragger()
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.TabPlaneDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.TabPlaneDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.TabPlaneDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.TabPlaneDragger_className(self)

    def handle(self, *args):
        """handle(self, PointerInfo pi, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter us) -> bool"""
        return _osgManipulator.TabPlaneDragger_handle(self, *args)

    def setupDefaultGeometry(self, twoSidedHandle = True):
        """
        setupDefaultGeometry(self, bool twoSidedHandle = True)
        setupDefaultGeometry(self)
        """
        return _osgManipulator.TabPlaneDragger_setupDefaultGeometry(self, twoSidedHandle)

    def setPlaneColor(self, *args):
        """setPlaneColor(self, Vec4 color)"""
        return _osgManipulator.TabPlaneDragger_setPlaneColor(self, *args)

TabPlaneDragger_swigregister = _osgManipulator.TabPlaneDragger_swigregister
TabPlaneDragger_swigregister(TabPlaneDragger)

OSGMANIPULATOR_TABPLANETRACKBALLDRAGGER = _osgManipulator.OSGMANIPULATOR_TABPLANETRACKBALLDRAGGER
class TabPlaneTrackballDragger(CompositeDragger):
    """Proxy of C++ osgManipulator::TabPlaneTrackballDragger class"""
    __swig_setmethods__ = {}
    for _s in [CompositeDragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TabPlaneTrackballDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [CompositeDragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TabPlaneTrackballDragger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> TabPlaneTrackballDragger"""
        this = _osgManipulator.new_TabPlaneTrackballDragger()
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.TabPlaneTrackballDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.TabPlaneTrackballDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.TabPlaneTrackballDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.TabPlaneTrackballDragger_className(self)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.TabPlaneTrackballDragger_setupDefaultGeometry(self)

    def setPlaneColor(self, *args):
        """setPlaneColor(self, Vec4 color)"""
        return _osgManipulator.TabPlaneTrackballDragger_setPlaneColor(self, *args)

TabPlaneTrackballDragger_swigregister = _osgManipulator.TabPlaneTrackballDragger_swigregister
TabPlaneTrackballDragger_swigregister(TabPlaneTrackballDragger)

OSGMANIPULATOR_TRACKBALLDRAGGER = _osgManipulator.OSGMANIPULATOR_TRACKBALLDRAGGER
class TrackballDragger(CompositeDragger):
    """Proxy of C++ osgManipulator::TrackballDragger class"""
    __swig_setmethods__ = {}
    for _s in [CompositeDragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TrackballDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [CompositeDragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TrackballDragger, name)
    __repr__ = _swig_repr
    def __init__(self, useAutoTransform = False): 
        """
        __init__(self, bool useAutoTransform = False) -> TrackballDragger
        __init__(self) -> TrackballDragger
        """
        this = _osgManipulator.new_TrackballDragger(useAutoTransform)
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.TrackballDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.TrackballDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.TrackballDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.TrackballDragger_className(self)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.TrackballDragger_setupDefaultGeometry(self)

TrackballDragger_swigregister = _osgManipulator.TrackballDragger_swigregister
TrackballDragger_swigregister(TrackballDragger)

OSGMANIPULATOR_TRANSLATE1DDRAGGER = _osgManipulator.OSGMANIPULATOR_TRANSLATE1DDRAGGER
class Translate1DDragger(Dragger):
    """Proxy of C++ osgManipulator::Translate1DDragger class"""
    __swig_setmethods__ = {}
    for _s in [Dragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Translate1DDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [Dragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Translate1DDragger, name)
    __repr__ = _swig_repr
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.Translate1DDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.Translate1DDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.Translate1DDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.Translate1DDragger_className(self)

    def __init__(self, *args): 
        """
        __init__(self) -> Translate1DDragger
        __init__(self, Vec3d s, Vec3d e) -> Translate1DDragger
        """
        this = _osgManipulator.new_Translate1DDragger(*args)
        try: self.this.append(this)
        except: self.this = this
    def handle(self, *args):
        """handle(self, PointerInfo pi, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter us) -> bool"""
        return _osgManipulator.Translate1DDragger_handle(self, *args)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.Translate1DDragger_setupDefaultGeometry(self)

    def setColor(self, *args):
        """setColor(self, Vec4 color)"""
        return _osgManipulator.Translate1DDragger_setColor(self, *args)

    def getColor(self):
        """getColor(self) -> Vec4"""
        return _osgManipulator.Translate1DDragger_getColor(self)

    def setPickColor(self, *args):
        """setPickColor(self, Vec4 color)"""
        return _osgManipulator.Translate1DDragger_setPickColor(self, *args)

    def getPickColor(self):
        """getPickColor(self) -> Vec4"""
        return _osgManipulator.Translate1DDragger_getPickColor(self)

    def setCheckForNodeInNodePath(self, *args):
        """setCheckForNodeInNodePath(self, bool onOff)"""
        return _osgManipulator.Translate1DDragger_setCheckForNodeInNodePath(self, *args)

Translate1DDragger_swigregister = _osgManipulator.Translate1DDragger_swigregister
Translate1DDragger_swigregister(Translate1DDragger)

OSGMANIPULATOR_TRANSLATE2DDRAGGER = _osgManipulator.OSGMANIPULATOR_TRANSLATE2DDRAGGER
class Translate2DDragger(Dragger):
    """Proxy of C++ osgManipulator::Translate2DDragger class"""
    __swig_setmethods__ = {}
    for _s in [Dragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Translate2DDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [Dragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Translate2DDragger, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> Translate2DDragger
        __init__(self, Plane plane) -> Translate2DDragger
        """
        this = _osgManipulator.new_Translate2DDragger(*args)
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.Translate2DDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.Translate2DDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.Translate2DDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.Translate2DDragger_className(self)

    def handle(self, *args):
        """handle(self, PointerInfo pi, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter us) -> bool"""
        return _osgManipulator.Translate2DDragger_handle(self, *args)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.Translate2DDragger_setupDefaultGeometry(self)

    def setColor(self, *args):
        """setColor(self, Vec4 color)"""
        return _osgManipulator.Translate2DDragger_setColor(self, *args)

    def getColor(self):
        """getColor(self) -> Vec4"""
        return _osgManipulator.Translate2DDragger_getColor(self)

    def setPickColor(self, *args):
        """setPickColor(self, Vec4 color)"""
        return _osgManipulator.Translate2DDragger_setPickColor(self, *args)

    def getPickColor(self):
        """getPickColor(self) -> Vec4"""
        return _osgManipulator.Translate2DDragger_getPickColor(self)

Translate2DDragger_swigregister = _osgManipulator.Translate2DDragger_swigregister
Translate2DDragger_swigregister(Translate2DDragger)

OSGMANIPULATOR_TRANSLATEAXISDRAGGER = _osgManipulator.OSGMANIPULATOR_TRANSLATEAXISDRAGGER
class TranslateAxisDragger(CompositeDragger):
    """Proxy of C++ osgManipulator::TranslateAxisDragger class"""
    __swig_setmethods__ = {}
    for _s in [CompositeDragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TranslateAxisDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [CompositeDragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TranslateAxisDragger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> TranslateAxisDragger"""
        this = _osgManipulator.new_TranslateAxisDragger()
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.TranslateAxisDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.TranslateAxisDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.TranslateAxisDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.TranslateAxisDragger_className(self)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.TranslateAxisDragger_setupDefaultGeometry(self)

TranslateAxisDragger_swigregister = _osgManipulator.TranslateAxisDragger_swigregister
TranslateAxisDragger_swigregister(TranslateAxisDragger)

OSGMANIPULATOR_TRANSLATEPLANEDRAGGER = _osgManipulator.OSGMANIPULATOR_TRANSLATEPLANEDRAGGER
class TranslatePlaneDragger(CompositeDragger):
    """Proxy of C++ osgManipulator::TranslatePlaneDragger class"""
    __swig_setmethods__ = {}
    for _s in [CompositeDragger]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TranslatePlaneDragger, name, value)
    __swig_getmethods__ = {}
    for _s in [CompositeDragger]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TranslatePlaneDragger, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(self) -> TranslatePlaneDragger"""
        this = _osgManipulator.new_TranslatePlaneDragger()
        try: self.this.append(this)
        except: self.this = this
    def cloneType(self):
        """cloneType(self) -> Object"""
        return _osgManipulator.TranslatePlaneDragger_cloneType(self)

    def isSameKindAs(self, *args):
        """isSameKindAs(self, Object obj) -> bool"""
        return _osgManipulator.TranslatePlaneDragger_isSameKindAs(self, *args)

    def libraryName(self):
        """libraryName(self) -> char"""
        return _osgManipulator.TranslatePlaneDragger_libraryName(self)

    def className(self):
        """className(self) -> char"""
        return _osgManipulator.TranslatePlaneDragger_className(self)

    def handle(self, *args):
        """handle(self, PointerInfo pi, osgGA::GUIEventAdapter ea, osgGA::GUIActionAdapter us) -> bool"""
        return _osgManipulator.TranslatePlaneDragger_handle(self, *args)

    def setupDefaultGeometry(self):
        """setupDefaultGeometry(self)"""
        return _osgManipulator.TranslatePlaneDragger_setupDefaultGeometry(self)

    def setColor(self, *args):
        """setColor(self, Vec4 color)"""
        return _osgManipulator.TranslatePlaneDragger_setColor(self, *args)

    def getTranslate1DDragger(self):
        """getTranslate1DDragger(self) -> Translate1DDragger"""
        return _osgManipulator.TranslatePlaneDragger_getTranslate1DDragger(self)

    def getTranslate2DDragger(self):
        """getTranslate2DDragger(self) -> Translate2DDragger"""
        return _osgManipulator.TranslatePlaneDragger_getTranslate2DDragger(self)

TranslatePlaneDragger_swigregister = _osgManipulator.TranslatePlaneDragger_swigregister
TranslatePlaneDragger_swigregister(TranslatePlaneDragger)


def NodeToDragger(*args):
  """NodeToDragger(Node d) -> Dragger"""
  return _osgManipulator.NodeToDragger(*args)

def NodeToSelection(*args):
  """NodeToSelection(Node d) -> Selection"""
  return _osgManipulator.NodeToSelection(*args)


