// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Feb 23 14:48:07 2012

#include <wx/wx.h>
#include <wx/image.h>
#include "ControlUI.h"



class DummyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(DummyApp)

bool DummyApp::OnInit()
{
    wxInitAllImageHandlers();
    ControlUI* control_frame = new ControlUI(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(control_frame);
    control_frame->Show();
    return true;
}
